BEGIN;
-- Chunk B: sections (compact SELECT-FROM-VALUES form) (part 1/2)
INSERT INTO sections (chapter_id, section_number, title, content_markdown, is_instructor_only, display_order)
SELECT c.id, v.section_number, v.title, '', v.is_instructor_only, v.display_order
FROM (VALUES
  (1, 1, '1', 'Learning Objectives', FALSE, 1),
  (1, 1, '2', 'What This System Is', FALSE, 2),
  (1, 1, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (1, 1, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (1, 1, '5', 'Inspection Process', FALSE, 5),
  (1, 1, '6', 'Common Failure Points', FALSE, 6),
  (1, 1, '7', 'Severity Rating Reference', FALSE, 7),
  (1, 1, '8', 'Maintenance Patterns', FALSE, 8),
  (1, 1, '9', 'Repair Approach', FALSE, 9),
  (1, 1, '10', 'Restoration Approach', FALSE, 10),
  (1, 1, '11', 'Replacement Approach', FALSE, 11),
  (1, 1, '12', 'Recommendation Decision Framework', FALSE, 12),
  (1, 1, '13', 'Disqualifying Conditions', FALSE, 13),
  (1, 1, '14', 'Sales Conversation Guide', FALSE, 14),
  (1, 1, '15', 'Lead Qualification Questions', FALSE, 15),
  (1, 1, '16', 'Customer Objection Handling', FALSE, 16),
  (1, 1, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (1, 1, '18', 'Common Sales Mistakes', FALSE, 18),
  (1, 1, '19', 'Warranty Reality', FALSE, 19),
  (1, 1, '20', 'Pricing Conversation Notes', FALSE, 20),
  (1, 1, '21', 'When to Escalate', FALSE, 21),
  (1, 1, '22', 'Company Method Box', FALSE, 22),
  (1, 1, '23', 'Instructor Notes', TRUE, 23),
  (1, 1, '24', 'Key Terms to Remember', FALSE, 24),
  (1, 1, '25', 'Chapter Summary', FALSE, 25),
  (1, 1, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (1, 1, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (1, 2, '1', 'Learning Objectives', FALSE, 1),
  (1, 2, '2', 'What This System Is', FALSE, 2),
  (1, 2, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (1, 2, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (1, 2, '5', 'Inspection Process', FALSE, 5),
  (1, 2, '6', 'Common Failure Points', FALSE, 6),
  (1, 2, '7', 'Severity Rating Reference', FALSE, 7),
  (1, 2, '8', 'Maintenance Patterns', FALSE, 8),
  (1, 2, '9', 'Repair Approach', FALSE, 9),
  (1, 2, '10', 'Restoration Approach', FALSE, 10),
  (1, 2, '11', 'Replacement Approach', FALSE, 11),
  (1, 2, '12', 'Recommendation Decision Framework', FALSE, 12),
  (1, 2, '13', 'Disqualifying Conditions', FALSE, 13),
  (1, 2, '14', 'Sales Conversation Guide', FALSE, 14),
  (1, 2, '15', 'Lead Qualification Questions', FALSE, 15),
  (1, 2, '16', 'Customer Objection Handling', FALSE, 16),
  (1, 2, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (1, 2, '18', 'Common Sales Mistakes', FALSE, 18),
  (1, 2, '19', 'Warranty Reality', FALSE, 19),
  (1, 2, '20', 'Pricing Conversation Notes', FALSE, 20),
  (1, 2, '21', 'When to Escalate', FALSE, 21),
  (1, 2, '22', 'Company Method Box', FALSE, 22),
  (1, 2, '23', 'Instructor Notes', TRUE, 23),
  (1, 2, '24', 'Key Terms to Remember', FALSE, 24),
  (1, 2, '25', 'Chapter Summary', FALSE, 25),
  (1, 2, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (1, 2, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (1, 3, '1', 'Learning Objectives', FALSE, 1),
  (1, 3, '2', 'What This System Is', FALSE, 2),
  (1, 3, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (1, 3, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (1, 3, '5', 'Inspection Process', FALSE, 5),
  (1, 3, '6', 'Common Failure Points', FALSE, 6),
  (1, 3, '7', 'Severity Rating Reference', FALSE, 7),
  (1, 3, '8', 'Maintenance Patterns', FALSE, 8),
  (1, 3, '9', 'Repair Approach', FALSE, 9),
  (1, 3, '10', 'Restoration Approach', FALSE, 10),
  (1, 3, '11', 'Replacement Approach', FALSE, 11),
  (1, 3, '12', 'Recommendation Decision Framework', FALSE, 12),
  (1, 3, '13', 'Disqualifying Conditions', FALSE, 13),
  (1, 3, '14', 'Sales Conversation Guide', FALSE, 14),
  (1, 3, '15', 'Lead Qualification Questions', FALSE, 15),
  (1, 3, '16', 'Customer Objection Handling', FALSE, 16),
  (1, 3, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (1, 3, '18', 'Common Sales Mistakes', FALSE, 18),
  (1, 3, '19', 'Warranty Reality', FALSE, 19),
  (1, 3, '20', 'Pricing Conversation Notes', FALSE, 20),
  (1, 3, '21', 'When to Escalate', FALSE, 21),
  (1, 3, '22', 'Company Method Box', FALSE, 22),
  (1, 3, '23', 'Instructor Notes', TRUE, 23),
  (1, 3, '24', 'Key Terms to Remember', FALSE, 24),
  (1, 3, '25', 'Chapter Summary', FALSE, 25),
  (1, 3, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (1, 3, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (1, 4, '1', 'Learning Objectives', FALSE, 1),
  (1, 4, '2', 'What This System Is', FALSE, 2),
  (1, 4, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (1, 4, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (1, 4, '5', 'Inspection Process', FALSE, 5),
  (1, 4, '6', 'Common Failure Points', FALSE, 6),
  (1, 4, '7', 'Severity Rating Reference', FALSE, 7),
  (1, 4, '8', 'Maintenance Patterns', FALSE, 8),
  (1, 4, '9', 'Repair Approach', FALSE, 9),
  (1, 4, '10', 'Restoration Approach', FALSE, 10),
  (1, 4, '11', 'Replacement Approach', FALSE, 11),
  (1, 4, '12', 'Recommendation Decision Framework', FALSE, 12),
  (1, 4, '13', 'Disqualifying Conditions', FALSE, 13),
  (1, 4, '14', 'Sales Conversation Guide', FALSE, 14),
  (1, 4, '15', 'Lead Qualification Questions', FALSE, 15),
  (1, 4, '16', 'Customer Objection Handling', FALSE, 16),
  (1, 4, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (1, 4, '18', 'Common Sales Mistakes', FALSE, 18),
  (1, 4, '19', 'Warranty Reality', FALSE, 19)
) AS v(part_num, chap_num, section_number, title, is_instructor_only, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
ON CONFLICT (chapter_id, section_number) DO NOTHING;
INSERT INTO sections (chapter_id, section_number, title, content_markdown, is_instructor_only, display_order)
SELECT c.id, v.section_number, v.title, '', v.is_instructor_only, v.display_order
FROM (VALUES
  (1, 4, '20', 'Pricing Conversation Notes', FALSE, 20),
  (1, 4, '21', 'When to Escalate', FALSE, 21),
  (1, 4, '22', 'Company Method Box', FALSE, 22),
  (1, 4, '23', 'Instructor Notes', TRUE, 23),
  (1, 4, '24', 'Key Terms to Remember', FALSE, 24),
  (1, 4, '25', 'Chapter Summary', FALSE, 25),
  (1, 4, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (1, 4, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (1, 5, '1', 'Learning Objectives', FALSE, 1),
  (1, 5, '2', 'What This System Is', FALSE, 2),
  (1, 5, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (1, 5, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (1, 5, '5', 'Inspection Process', FALSE, 5),
  (1, 5, '6', 'Common Failure Points', FALSE, 6),
  (1, 5, '7', 'Severity Rating Reference', FALSE, 7),
  (1, 5, '8', 'Maintenance Patterns', FALSE, 8),
  (1, 5, '9', 'Repair Approach', FALSE, 9),
  (1, 5, '10', 'Restoration Approach', FALSE, 10),
  (1, 5, '11', 'Replacement Approach', FALSE, 11),
  (1, 5, '12', 'Recommendation Decision Framework', FALSE, 12),
  (1, 5, '13', 'Disqualifying Conditions', FALSE, 13),
  (1, 5, '14', 'Sales Conversation Guide', FALSE, 14),
  (1, 5, '15', 'Lead Qualification Questions', FALSE, 15),
  (1, 5, '16', 'Customer Objection Handling', FALSE, 16),
  (1, 5, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (1, 5, '18', 'Common Sales Mistakes', FALSE, 18),
  (1, 5, '19', 'Warranty Reality', FALSE, 19),
  (1, 5, '20', 'Pricing Conversation Notes', FALSE, 20),
  (1, 5, '21', 'When to Escalate', FALSE, 21),
  (1, 5, '22', 'Company Method Box', FALSE, 22),
  (1, 5, '23', 'Instructor Notes', TRUE, 23),
  (1, 5, '24', 'Key Terms to Remember', FALSE, 24),
  (1, 5, '25', 'Chapter Summary', FALSE, 25),
  (1, 5, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (1, 5, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (1, 6, '1', 'Learning Objectives', FALSE, 1),
  (1, 6, '2', 'What This System Is', FALSE, 2),
  (1, 6, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (1, 6, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (1, 6, '5', 'Inspection Process', FALSE, 5),
  (1, 6, '6', 'Common Failure Points', FALSE, 6),
  (1, 6, '7', 'Severity Rating Reference', FALSE, 7),
  (1, 6, '8', 'Maintenance Patterns', FALSE, 8),
  (1, 6, '9', 'Repair Approach', FALSE, 9),
  (1, 6, '10', 'Restoration Approach', FALSE, 10),
  (1, 6, '11', 'Replacement Approach', FALSE, 11),
  (1, 6, '12', 'Recommendation Decision Framework', FALSE, 12),
  (1, 6, '13', 'Disqualifying Conditions', FALSE, 13),
  (1, 6, '14', 'Sales Conversation Guide', FALSE, 14),
  (1, 6, '15', 'Lead Qualification Questions', FALSE, 15),
  (1, 6, '16', 'Customer Objection Handling', FALSE, 16),
  (1, 6, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (1, 6, '18', 'Common Sales Mistakes', FALSE, 18),
  (1, 6, '19', 'Warranty Reality', FALSE, 19),
  (1, 6, '20', 'Pricing Conversation Notes', FALSE, 20),
  (1, 6, '21', 'When to Escalate', FALSE, 21),
  (1, 6, '22', 'Company Method Box', FALSE, 22),
  (1, 6, '23', 'Instructor Notes', TRUE, 23),
  (1, 6, '24', 'Key Terms to Remember', FALSE, 24),
  (1, 6, '25', 'Chapter Summary', FALSE, 25),
  (1, 6, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (1, 6, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (1, 8, '1', 'Learning Objectives', FALSE, 1),
  (1, 8, '2', 'What This System Is', FALSE, 2),
  (1, 8, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (1, 8, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (1, 8, '5', 'Inspection Process', FALSE, 5),
  (1, 8, '6', 'Common Failure Points', FALSE, 6),
  (1, 8, '7', 'Severity Rating Reference', FALSE, 7),
  (1, 8, '8', 'Maintenance Patterns', FALSE, 8),
  (1, 8, '9', 'Repair Approach', FALSE, 9),
  (1, 8, '10', 'Restoration Approach', FALSE, 10),
  (1, 8, '11', 'Replacement Approach', FALSE, 11),
  (1, 8, '12', 'Recommendation Decision Framework', FALSE, 12),
  (1, 8, '13', 'Disqualifying Conditions', FALSE, 13),
  (1, 8, '14', 'Sales Conversation Guide', FALSE, 14),
  (1, 8, '15', 'Lead Qualification Questions', FALSE, 15),
  (1, 8, '16', 'Customer Objection Handling', FALSE, 16),
  (1, 8, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (1, 8, '18', 'Common Sales Mistakes', FALSE, 18),
  (1, 8, '19', 'Warranty Reality', FALSE, 19),
  (1, 8, '20', 'Pricing Conversation Notes', FALSE, 20),
  (1, 8, '21', 'When to Escalate', FALSE, 21),
  (1, 8, '22', 'Company Method Box', FALSE, 22),
  (1, 8, '23', 'Instructor Notes', TRUE, 23),
  (1, 8, '24', 'Key Terms to Remember', FALSE, 24),
  (1, 8, '25', 'Chapter Summary', FALSE, 25),
  (1, 8, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (1, 8, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (1, 9, '1', 'Learning Objectives', FALSE, 1),
  (1, 9, '2', 'What This System Is', FALSE, 2),
  (1, 9, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (1, 9, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (1, 9, '5', 'Inspection Process', FALSE, 5),
  (1, 9, '6', 'Common Failure Points', FALSE, 6),
  (1, 9, '7', 'Severity Rating Reference', FALSE, 7),
  (1, 9, '8', 'Maintenance Patterns', FALSE, 8),
  (1, 9, '9', 'Repair Approach', FALSE, 9),
  (1, 9, '10', 'Restoration Approach', FALSE, 10),
  (1, 9, '11', 'Replacement Approach', FALSE, 11)
) AS v(part_num, chap_num, section_number, title, is_instructor_only, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
ON CONFLICT (chapter_id, section_number) DO NOTHING;
INSERT INTO sections (chapter_id, section_number, title, content_markdown, is_instructor_only, display_order)
SELECT c.id, v.section_number, v.title, '', v.is_instructor_only, v.display_order
FROM (VALUES
  (1, 9, '12', 'Recommendation Decision Framework', FALSE, 12),
  (1, 9, '13', 'Disqualifying Conditions', FALSE, 13),
  (1, 9, '14', 'Sales Conversation Guide', FALSE, 14),
  (1, 9, '15', 'Lead Qualification Questions', FALSE, 15),
  (1, 9, '16', 'Customer Objection Handling', FALSE, 16),
  (1, 9, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (1, 9, '18', 'Common Sales Mistakes', FALSE, 18),
  (1, 9, '19', 'Warranty Reality', FALSE, 19),
  (1, 9, '20', 'Pricing Conversation Notes', FALSE, 20),
  (1, 9, '21', 'When to Escalate', FALSE, 21),
  (1, 9, '22', 'Company Method Box', FALSE, 22),
  (1, 9, '23', 'Instructor Notes', TRUE, 23),
  (1, 9, '24', 'Key Terms to Remember', FALSE, 24),
  (1, 9, '25', 'Chapter Summary', FALSE, 25),
  (1, 9, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (1, 9, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (1, 10, '1', 'Learning Objectives', FALSE, 1),
  (1, 10, '2', 'What This System Is', FALSE, 2),
  (1, 10, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (1, 10, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (1, 10, '5', 'Inspection Process', FALSE, 5),
  (1, 10, '6', 'Common Failure Points', FALSE, 6),
  (1, 10, '7', 'Severity Rating Reference', FALSE, 7),
  (1, 10, '8', 'Maintenance Patterns', FALSE, 8),
  (1, 10, '9', 'Repair Approach', FALSE, 9),
  (1, 10, '10', 'Restoration Approach', FALSE, 10),
  (1, 10, '11', 'Replacement Approach', FALSE, 11),
  (1, 10, '12', 'Recommendation Decision Framework', FALSE, 12),
  (1, 10, '13', 'Disqualifying Conditions', FALSE, 13),
  (1, 10, '14', 'Sales Conversation Guide', FALSE, 14),
  (1, 10, '15', 'Lead Qualification Questions', FALSE, 15),
  (1, 10, '16', 'Customer Objection Handling', FALSE, 16),
  (1, 10, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (1, 10, '18', 'Common Sales Mistakes', FALSE, 18),
  (1, 10, '19', 'Warranty Reality', FALSE, 19),
  (1, 10, '20', 'Pricing Conversation Notes', FALSE, 20),
  (1, 10, '21', 'When to Escalate', FALSE, 21),
  (1, 10, '22', 'Company Method Box', FALSE, 22),
  (1, 10, '23', 'Instructor Notes', TRUE, 23),
  (1, 10, '24', 'Key Terms to Remember', FALSE, 24),
  (1, 10, '25', 'Chapter Summary', FALSE, 25),
  (1, 10, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (1, 10, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (2, 11, '1', 'Learning Objectives', FALSE, 1),
  (2, 11, '2', 'What This System Is', FALSE, 2),
  (2, 11, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (2, 11, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (2, 11, '5', 'Inspection Process', FALSE, 5),
  (2, 11, '6', 'Common Failure Points', FALSE, 6),
  (2, 11, '7', 'Severity Rating Reference', FALSE, 7),
  (2, 11, '8', 'Maintenance Patterns', FALSE, 8),
  (2, 11, '9', 'Repair Approach', FALSE, 9),
  (2, 11, '10', 'Restoration Approach', FALSE, 10),
  (2, 11, '11', 'Replacement Approach', FALSE, 11),
  (2, 11, '12', 'Recommendation Decision Framework', FALSE, 12),
  (2, 11, '13', 'Disqualifying Conditions', FALSE, 13),
  (2, 11, '14', 'Sales Conversation Guide', FALSE, 14),
  (2, 11, '15', 'Lead Qualification Questions', FALSE, 15),
  (2, 11, '16', 'Customer Objection Handling', FALSE, 16),
  (2, 11, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (2, 11, '18', 'Common Sales Mistakes', FALSE, 18),
  (2, 11, '19', 'Warranty Reality', FALSE, 19),
  (2, 11, '20', 'Pricing Conversation Notes', FALSE, 20),
  (2, 11, '21', 'When to Escalate', FALSE, 21),
  (2, 11, '22', 'Company Method Box', FALSE, 22),
  (2, 11, '23', 'Instructor Notes', TRUE, 23),
  (2, 11, '24', 'Key Terms to Remember', FALSE, 24),
  (2, 11, '25', 'Chapter Summary', FALSE, 25),
  (2, 11, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (2, 11, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (2, 12, '1', 'Learning Objectives', FALSE, 1),
  (2, 12, '2', 'What This System Is', FALSE, 2),
  (2, 12, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (2, 12, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (2, 12, '5', 'Inspection Process', FALSE, 5),
  (2, 12, '6', 'Common Failure Points', FALSE, 6),
  (2, 12, '7', 'Severity Rating Reference', FALSE, 7),
  (2, 12, '8', 'Maintenance Patterns', FALSE, 8),
  (2, 12, '9', 'Repair Approach', FALSE, 9),
  (2, 12, '10', 'Restoration Approach', FALSE, 10),
  (2, 12, '11', 'Replacement Approach', FALSE, 11),
  (2, 12, '12', 'Recommendation Decision Framework', FALSE, 12),
  (2, 12, '13', 'Disqualifying Conditions', FALSE, 13),
  (2, 12, '14', 'Sales Conversation Guide', FALSE, 14),
  (2, 12, '15', 'Lead Qualification Questions', FALSE, 15),
  (2, 12, '16', 'Customer Objection Handling', FALSE, 16),
  (2, 12, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (2, 12, '18', 'Common Sales Mistakes', FALSE, 18),
  (2, 12, '19', 'Warranty Reality', FALSE, 19),
  (2, 12, '20', 'Pricing Conversation Notes', FALSE, 20),
  (2, 12, '21', 'When to Escalate', FALSE, 21),
  (2, 12, '22', 'Company Method Box', FALSE, 22),
  (2, 12, '23', 'Instructor Notes', TRUE, 23),
  (2, 12, '24', 'Key Terms to Remember', FALSE, 24),
  (2, 12, '25', 'Chapter Summary', FALSE, 25),
  (2, 12, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (2, 12, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (2, 13, '1', 'Learning Objectives', FALSE, 1),
  (2, 13, '2', 'What This System Is', FALSE, 2),
  (2, 13, '3', 'Where USA Flat Roof Uses It', FALSE, 3)
) AS v(part_num, chap_num, section_number, title, is_instructor_only, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
ON CONFLICT (chapter_id, section_number) DO NOTHING;
INSERT INTO sections (chapter_id, section_number, title, content_markdown, is_instructor_only, display_order)
SELECT c.id, v.section_number, v.title, '', v.is_instructor_only, v.display_order
FROM (VALUES
  (2, 13, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (2, 13, '5', 'Inspection Process', FALSE, 5),
  (2, 13, '6', 'Common Failure Points', FALSE, 6),
  (2, 13, '7', 'Severity Rating Reference', FALSE, 7),
  (2, 13, '8', 'Maintenance Patterns', FALSE, 8),
  (2, 13, '9', 'Repair Approach', FALSE, 9),
  (2, 13, '10', 'Restoration Approach', FALSE, 10),
  (2, 13, '11', 'Replacement Approach', FALSE, 11),
  (2, 13, '12', 'Recommendation Decision Framework', FALSE, 12),
  (2, 13, '13', 'Disqualifying Conditions', FALSE, 13),
  (2, 13, '14', 'Sales Conversation Guide', FALSE, 14),
  (2, 13, '15', 'Lead Qualification Questions', FALSE, 15),
  (2, 13, '16', 'Customer Objection Handling', FALSE, 16),
  (2, 13, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (2, 13, '18', 'Common Sales Mistakes', FALSE, 18),
  (2, 13, '19', 'Warranty Reality', FALSE, 19),
  (2, 13, '20', 'Pricing Conversation Notes', FALSE, 20),
  (2, 13, '21', 'When to Escalate', FALSE, 21),
  (2, 13, '22', 'Company Method Box', FALSE, 22),
  (2, 13, '23', 'Instructor Notes', TRUE, 23),
  (2, 13, '24', 'Key Terms to Remember', FALSE, 24),
  (2, 13, '25', 'Chapter Summary', FALSE, 25),
  (2, 13, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (2, 13, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (2, 14, '1', 'Learning Objectives', FALSE, 1),
  (2, 14, '2', 'What This System Is', FALSE, 2),
  (2, 14, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (2, 14, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (2, 14, '5', 'Inspection Process', FALSE, 5),
  (2, 14, '6', 'Common Failure Points', FALSE, 6),
  (2, 14, '7', 'Severity Rating Reference', FALSE, 7),
  (2, 14, '8', 'Maintenance Patterns', FALSE, 8),
  (2, 14, '9', 'Repair Approach', FALSE, 9),
  (2, 14, '10', 'Restoration Approach', FALSE, 10),
  (2, 14, '11', 'Replacement Approach', FALSE, 11),
  (2, 14, '12', 'Recommendation Decision Framework', FALSE, 12),
  (2, 14, '13', 'Disqualifying Conditions', FALSE, 13),
  (2, 14, '14', 'Sales Conversation Guide', FALSE, 14),
  (2, 14, '15', 'Lead Qualification Questions', FALSE, 15),
  (2, 14, '16', 'Customer Objection Handling', FALSE, 16),
  (2, 14, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (2, 14, '18', 'Common Sales Mistakes', FALSE, 18),
  (2, 14, '19', 'Warranty Reality', FALSE, 19),
  (2, 14, '20', 'Pricing Conversation Notes', FALSE, 20),
  (2, 14, '21', 'When to Escalate', FALSE, 21),
  (2, 14, '22', 'Company Method Box', FALSE, 22),
  (2, 14, '23', 'Instructor Notes', TRUE, 23),
  (2, 14, '24', 'Key Terms to Remember', FALSE, 24),
  (2, 14, '25', 'Chapter Summary', FALSE, 25),
  (2, 14, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (2, 14, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (2, 15, '1', 'Learning Objectives', FALSE, 1),
  (2, 15, '2', 'What This System Is', FALSE, 2),
  (2, 15, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (2, 15, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (2, 15, '5', 'Inspection Process', FALSE, 5),
  (2, 15, '6', 'Common Failure Points', FALSE, 6),
  (2, 15, '7', 'Severity Rating Reference', FALSE, 7),
  (2, 15, '8', 'Maintenance Patterns', FALSE, 8),
  (2, 15, '9', 'Repair Approach', FALSE, 9),
  (2, 15, '10', 'Restoration Approach', FALSE, 10),
  (2, 15, '11', 'Replacement Approach', FALSE, 11),
  (2, 15, '12', 'Recommendation Decision Framework', FALSE, 12),
  (2, 15, '13', 'Disqualifying Conditions', FALSE, 13),
  (2, 15, '14', 'Sales Conversation Guide', FALSE, 14),
  (2, 15, '15', 'Lead Qualification Questions', FALSE, 15),
  (2, 15, '16', 'Customer Objection Handling', FALSE, 16),
  (2, 15, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (2, 15, '18', 'Common Sales Mistakes', FALSE, 18),
  (2, 15, '19', 'Warranty Reality', FALSE, 19),
  (2, 15, '20', 'Pricing Conversation Notes', FALSE, 20),
  (2, 15, '21', 'When to Escalate', FALSE, 21),
  (2, 15, '22', 'Company Method Box', FALSE, 22),
  (2, 15, '23', 'Instructor Notes', TRUE, 23),
  (2, 15, '24', 'Key Terms to Remember', FALSE, 24),
  (2, 15, '25', 'Chapter Summary', FALSE, 25),
  (2, 15, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (2, 15, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (2, 16, '1', 'Learning Objectives', FALSE, 1),
  (2, 16, '2', 'What This System Is', FALSE, 2),
  (2, 16, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (2, 16, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (2, 16, '5', 'Inspection Process', FALSE, 5),
  (2, 16, '6', 'Common Failure Points', FALSE, 6),
  (2, 16, '7', 'Severity Rating Reference', FALSE, 7),
  (2, 16, '8', 'Maintenance Patterns', FALSE, 8),
  (2, 16, '9', 'Repair Approach', FALSE, 9),
  (2, 16, '10', 'Restoration Approach', FALSE, 10),
  (2, 16, '11', 'Replacement Approach', FALSE, 11),
  (2, 16, '12', 'Recommendation Decision Framework', FALSE, 12),
  (2, 16, '13', 'Disqualifying Conditions', FALSE, 13),
  (2, 16, '14', 'Sales Conversation Guide', FALSE, 14),
  (2, 16, '15', 'Lead Qualification Questions', FALSE, 15),
  (2, 16, '16', 'Customer Objection Handling', FALSE, 16),
  (2, 16, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (2, 16, '18', 'Common Sales Mistakes', FALSE, 18),
  (2, 16, '19', 'Warranty Reality', FALSE, 19),
  (2, 16, '20', 'Pricing Conversation Notes', FALSE, 20),
  (2, 16, '21', 'When to Escalate', FALSE, 21),
  (2, 16, '22', 'Company Method Box', FALSE, 22)
) AS v(part_num, chap_num, section_number, title, is_instructor_only, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
ON CONFLICT (chapter_id, section_number) DO NOTHING;
COMMIT;
