BEGIN;
-- Chunk C: final exam quiz + sections + questions + answers (part 3/3)
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (61, 'A', 'Agree with the customer', FALSE, 'Legitimate rejuvenation chemistry exists.', 1),
  (61, 'B', 'Acknowledge the concern, explain the chemistry, and emphasize the qualification process', TRUE, 'Honest response. Reference: Module 5, Chapter 4.', 2),
  (61, 'C', 'Insist the product works regardless', FALSE, 'Pressure tactic; doesn''t address the concern.', 3),
  (61, 'D', 'Refer the customer elsewhere', FALSE, 'Engagement is appropriate.', 4),
  (62, 'A', 'Quote a patch on the area above the staining', FALSE, 'Patching without identified source is wrong.', 1),
  (62, 'B', 'Decline the work', FALSE, 'Customer still deserves engagement.', 2),
  (62, 'C', 'Document inspection findings, flag the possibility of vapor or assembly moisture issues, and escalate for moisture survey or qualified assembly assessment before quoting', TRUE, 'Vapor concern requires escalation. Reference: Chapter 14.', 3),
  (62, 'D', 'Recommend restoration coating', FALSE, 'Restoration on roof without inspection-identified issue is overselling.', 4),
  (63, 'A', 'Improved ventilation through redundancy', FALSE, 'Redundancy doesn''t help; short-circuit is the result.', 1),
  (63, 'B', 'A short-circuit pattern where the two exhaust types pull from each other instead of pulling air through the full attic', TRUE, 'Common ventilation configuration error. Reference: Chapter 14.', 2),
  (63, 'C', 'Better cooling in summer only', FALSE, 'Short-circuit reduces effectiveness across seasons.', 3),
  (63, 'D', 'No effect on ventilation', FALSE, 'Significant negative effect.', 4),
  (64, 'A', 'Skip the ventilation work without further comment', FALSE, 'Honest engagement requires explanation.', 1),
  (64, 'B', 'Insist the customer accept the ventilation upgrade', FALSE, 'Pressure tactic.', 2),
  (64, 'C', 'Explain that ventilation drives how long the new roof lasts and may affect manufacturer warranty coverage; document the conversation if the customer still declines', TRUE, 'Honest framework. Reference: Chapter 14.', 3),
  (64, 'D', 'Refer the customer elsewhere', FALSE, 'Engagement is appropriate.', 4),
  (65, 'A', 'Apologize and reduce inspection scope', FALSE, 'Reducing scope creates downstream problems.', 1),
  (65, 'B', 'Skip documentation', FALSE, 'Documentation is part of standard scope.', 2),
  (65, 'C', 'Explain that documentation protects them for warranty, insurance, and resale, and that pricing will be accurate because the scope is real', TRUE, 'Honest framing. Reference: Module 7, Module 11.', 3),
  (65, 'D', 'Bill the customer for documentation time', FALSE, 'Documentation is part of standard inspection.', 4),
  (66, 'A', 'Mineral granules embedded in the asphalt', TRUE, 'Standard composition shingle definition. Reference: Chapter 1.', 1),
  (66, 'B', 'Aluminum foil', FALSE, 'Not the standard surface.', 2),
  (66, 'C', 'Plastic film', FALSE, 'Not the standard surface.', 3),
  (66, 'D', 'Nothing — the asphalt is exposed', FALSE, 'Granules protect the asphalt.', 4),
  (67, 'A', 'The tiles themselves', FALSE, 'Tiles are the weather covering, not the waterproofing.', 1),
  (67, 'B', 'The underlayment beneath the tiles', TRUE, 'Central tile fact. Reference: Chapter 8.', 2),
  (67, 'C', 'The mortar at the ridge', FALSE, 'Mortar is decorative/structural at ridge, not waterproofing.', 3),
  (67, 'D', 'The flashings only', FALSE, 'Flashings are details, not the primary layer.', 4),
  (68, 'A', '5–10 years', FALSE, 'Tiles last much longer.', 1),
  (68, 'B', '15–20 years', FALSE, 'Underlayment lifespan, not tile lifespan.', 2),
  (68, 'C', '50+ years', TRUE, 'Standard tile lifespan. Reference: Chapter 8.', 3),
  (68, 'D', 'Forever', FALSE, 'Tiles eventually fail.', 4),
  (69, 'A', 'Adhesive bonding', FALSE, 'Not the TPO method.', 1),
  (69, 'B', 'Self-adhesive tape', FALSE, 'Not the TPO method.', 2),
  (69, 'C', 'Hot-air welding', TRUE, 'TPO is thermoplastic. Reference: Chapter 2.', 3),
  (69, 'D', 'Mechanical clamping', FALSE, 'Mechanical attachment is field; seams are welded.', 4),
  (70, 'A', 'The base sheet', FALSE, 'Base sheet is multi-ply terminology.', 1),
  (70, 'B', 'The topcoat', TRUE, 'Required for UV protection. Reference: Chapter 10.', 2),
  (70, 'C', 'The cap sheet', FALSE, 'Cap sheet is mod-bit terminology.', 3),
  (70, 'D', 'The flashing', FALSE, 'Flashing is a detail, not the field protection.', 4),
  (71, 'A', 'Torch-down only', FALSE, 'USA Flat Roof doesn''t use torch-down.', 1),
  (71, 'B', 'Hot-mopped only', FALSE, 'USA Flat Roof doesn''t use hot-mopped.', 2),
  (71, 'C', 'Self-adhered (peel-and-stick) only', TRUE, 'Specific to USA Flat Roof. Reference: Chapter 6.', 3),
  (71, 'D', 'All three methods', FALSE, 'Self-adhered only.', 4),
  (72, 'A', 'Asphalt shingle roofs only', TRUE, 'Standard rejuvenation scope. Reference: Chapter 4.', 1),
  (72, 'B', 'All roof types including tile, metal, and flat roofs', FALSE, 'Specifically for asphalt shingle.', 2),
  (72, 'C', 'Flat commercial roofs primarily', FALSE, 'Not for flat commercial.', 3),
  (72, 'D', 'Wood shake and slate roofs', FALSE, 'Not for wood or slate.', 4),
  (73, 'A', 'The coating product, but not the substrate underneath', TRUE, 'Critical warranty point. Reference: Chapter 3, Module 12.', 1),
  (73, 'B', 'The full roof system including substrate failures', FALSE, 'Substrate not covered by coating warranty.', 2),
  (73, 'C', 'Only manufacturing defects, not application', FALSE, 'Coverage extends beyond manufacturing.', 3),
  (73, 'D', 'All leaks regardless of cause', FALSE, 'Coverage has specific terms.', 4),
  (74, 'A', 'PVC is required by California building code', FALSE, 'Not a code requirement.', 1),
  (74, 'B', 'PVC''s grease and chemical resistance is significantly better than TPO''s', TRUE, 'Technical reason for restaurant specification. Reference: Chapter 5.', 2),
  (74, 'C', 'PVC is more reflective', FALSE, 'Reflectivity is similar.', 3),
  (74, 'D', 'PVC weighs less', FALSE, 'Weight isn''t the primary reason.', 4),
  (75, 'A', 'Granule loss', FALSE, 'PVC has no granules.', 1),
  (75, 'B', 'Plasticizer migration leading to stiffening and brittleness', TRUE, 'Primary aging mechanism. Reference: Chapter 5.', 2),
  (75, 'C', 'UV color change', FALSE, 'Not the primary mechanism.', 3),
  (75, 'D', 'Seam adhesive degradation', FALSE, 'PVC seams are welded, not adhesive.', 4),
  (76, 'A', 'About 5 to 10 years', FALSE, 'Too short.', 1),
  (76, 'B', 'About 18 to 25 years', TRUE, 'NorCal field range. Reference: Chapter 2.', 2),
  (76, 'C', 'Exactly 30 years', FALSE, 'Specific numbers aren''t accurate.', 3),
  (76, 'D', 'Over 50 years', FALSE, 'Beyond expected service life.', 4),
  (77, 'A', 'Manufacturer defects', FALSE, 'Not the primary cause.', 1),
  (77, 'B', 'UV degradation cracking the rubber, particularly at the top where the boot wraps the pipe', TRUE, 'Most common failure mechanism. Reference: Chapter 15.', 2),
  (77, 'C', 'Wind damage', FALSE, 'Less common than UV.', 3),
  (77, 'D', 'Snow load', FALSE, 'Not relevant to NorCal residential.', 4),
  (78, 'A', 'Significantly longer service life', FALSE, 'Service life is similar.', 1),
  (78, 'B', 'Lower material cost', FALSE, 'Not the primary advantage.', 2),
  (78, 'C', 'No open flame during installation, eliminating fire risk', TRUE, 'Central reason for self-adhered choice. Reference: Chapter 6.', 3),
  (78, 'D', 'Faster cure time', FALSE, 'Not the primary advantage.', 4),
  (79, 'A', 'Residential roofs, decorative roofs, and metal recover', FALSE, 'Not the USA Flat Roof use cases.', 1),
  (79, 'B', 'Ponding water correction, BUR recover after gravel removal, and insulation upgrade', TRUE, 'USA Flat Roof''s specific positioning. Reference: Chapter 10.', 2),
  (79, 'C', 'Steep-slope shingle replacement, parapet flashing, and chimney work', FALSE, 'Not appropriate SPF applications.', 3),
  (79, 'D', 'Emergency leak repair, attic ventilation, and skylight installation', FALSE, 'Not appropriate SPF applications.', 4),
  (80, 'A', 'Quote the manufacturer''s marketing maximum', FALSE, 'Marketing maximum isn''t realistic for all roofs.', 1),
  (80, 'B', 'Refer to the manufacturer''s published extension range and note that actual results depend on roof condition and maintenance', TRUE, 'Honest framework. Reference: Chapter 4, Module 5.', 2),
  (80, 'C', 'Promise a specific number of years', FALSE, 'Specific numbers are guesses.', 3),
  (80, 'D', 'Tell the customer rejuvenation has no defined extension', FALSE, 'Manufacturer publishes ranges.', 4)
) AS v(question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN quizzes q ON q.is_final_exam = TRUE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (81, 'A', 'TPO overlay', FALSE, 'TPO doesn''t correct slope.', 1),
  (81, 'B', 'SPF', TRUE, 'Unique among standard flat-roof systems for slope correction. Reference: Chapter 10, Chapter 16.', 2),
  (81, 'C', 'Silicone coating', FALSE, 'Coatings don''t add slope.', 3),
  (81, 'D', 'Modified bitumen', FALSE, 'Mod-bit doesn''t correct slope.', 4),
  (82, 'A', 'TPO', FALSE, 'TPO is more recent than BUR.', 1),
  (82, 'B', 'Silicone coating', FALSE, 'Restoration product, more recent.', 2),
  (82, 'C', 'BUR (Built-Up Roofing)', TRUE, 'Longest documented field track record. Reference: Chapter 9.', 3),
  (82, 'D', 'SPF', FALSE, 'More recent than BUR.', 4),
  (83, 'A', 'Tolerate ponding water better', FALSE, 'Acrylic tolerates ponding less well than silicone.', 1),
  (83, 'B', 'Tolerate ponding water less well; tend to be lower cost; recoat more flexibly with other chemistries', TRUE, 'Standard comparison. Reference: Chapter 7, Table 6.', 2),
  (83, 'C', 'Last longer', FALSE, 'Generally shorter service life than silicone.', 3),
  (83, 'D', 'Require less prep', FALSE, 'Prep requirements similar.', 4),
  (84, 'A', 'Lower cost with comparable performance', FALSE, 'PVC is higher cost.', 1),
  (84, 'B', 'Higher cost with premium positioning, longer track record, and better grease/chemical resistance', TRUE, 'Standard comparison. Reference: Chapter 5, Table 2.', 2),
  (84, 'C', 'Available only in black', FALSE, 'PVC is typically white.', 3),
  (84, 'D', 'Used only on residential', FALSE, 'PVC is commercial.', 4),
  (85, 'A', 'Silicone coating', FALSE, 'Silicone doesn''t apply to shingle.', 1),
  (85, 'B', 'Fresh Roof rejuvenation if the roof is in the qualifying window', TRUE, 'Standard mid-life shingle recommendation. Reference: Chapter 1, Chapter 4.', 2),
  (85, 'C', 'Full replacement', FALSE, 'Premature on mid-life roof with sound substrate.', 3),
  (85, 'D', 'SPF', FALSE, 'SPF doesn''t apply to shingle.', 4),
  (86, 'A', 'Faster installation', FALSE, 'Generally slower than single-ply.', 1),
  (86, 'B', 'Multi-ply redundancy and asphalt-based proven chemistry', TRUE, 'Standard mod-bit comparison. Reference: Chapter 6.', 2),
  (86, 'C', 'Lighter weight', FALSE, 'Heavier than single-ply.', 3),
  (86, 'D', 'Lower up-front cost in all cases', FALSE, 'Cost varies by scope.', 4),
  (87, 'A', 'The cheaper one is always a worse deal', FALSE, 'Not always; scope determines value.', 1),
  (87, 'B', 'The price by itself; cheaper is better', FALSE, 'Price alone isn''t the meaningful comparison.', 2),
  (87, 'C', 'Scope differences (mil thickness, prep, fabric reinforcement, detail repair, warranty tier) — not the price alone', TRUE, 'Standard comparison framing. Reference: Module 4, Module 11.', 3),
  (87, 'D', 'Brand reputation only', FALSE, 'Reputation matters but scope is the primary comparison.', 4),
  (88, 'A', 'Quote BUR replacement to capture the work', FALSE, 'USA Flat Roof doesn''t install new BUR.', 1),
  (88, 'B', 'Decline without explanation', FALSE, 'Explanation is part of honest engagement.', 2),
  (88, 'C', 'Explain that USA Flat Roof does not install new BUR, present alternatives, and offer to refer to a BUR specialty contractor if they prefer like-for-like', TRUE, 'Honest positioning. Reference: Chapter 9.', 3),
  (88, 'D', 'Recommend silicone restoration regardless', FALSE, 'Restoration may not be appropriate; depends on inspection.', 4),
  (89, 'A', 'The same recommendation as the shingle', FALSE, 'Different system requires different recommendation.', 1),
  (89, 'B', 'Its own separate inspection and recommendation, applying the commercial-system framework', TRUE, 'Standard mixed-roof handling. Reference: Chapter 17, Chapter 18.', 2),
  (89, 'C', 'Replacement of the entire roof together', FALSE, 'Often inappropriate to bundle.', 3),
  (89, 'D', 'No inspection — flat sections are not part of residential scope', FALSE, 'Flat sections are part of the home.', 4),
  (90, 'A', 'The center of the roof field', FALSE, 'Field is the easiest part to waterproof.', 1),
  (90, 'B', 'Penetrations, transitions (walls, parapets), edges, and valleys / drains', TRUE, 'Universal failure pattern. Reference: Chapter 15, Table 7.', 2),
  (90, 'C', 'Random locations with no pattern', FALSE, 'Patterns exist.', 3),
  (90, 'D', 'The deck only', FALSE, 'Deck failures are rare.', 4),
  (91, 'A', 'Match their price immediately', FALSE, 'Capitulation damages the deal and trust.', 1),
  (91, 'B', 'Decline to engage', FALSE, 'Engagement is appropriate.', 2),
  (91, 'C', 'Acknowledge that price differences usually reflect scope differences and offer to walk through the comparison', TRUE, 'Standard pricing comparison framing. Reference: Module 4, Module 11.', 3),
  (91, 'D', 'Discount the proposal automatically', FALSE, 'Discounting on the same scope creates problems.', 4),
  (92, 'A', 'Patch as requested without comment', FALSE, 'Repeated repairs warrant the broader conversation.', 1),
  (92, 'B', 'Explain that repeat repairs on a roof of this age are short-term spending, recommend an inspection, and present replacement options if findings support it', TRUE, 'Standard repeat-leak pattern. Reference: Chapter 11, Module 9.', 2),
  (92, 'C', 'Decline the work', FALSE, 'Engagement is appropriate.', 3),
  (92, 'D', 'Recommend silicone coating immediately', FALSE, 'Recommendation requires inspection.', 4),
  (93, 'A', 'Defer to the other contractor''s assessment', FALSE, 'Document and explain what was observed.', 1),
  (93, 'B', 'Tell the customer the other contractor was wrong', FALSE, 'Bashing is unprofessional.', 2),
  (93, 'C', 'Document what you observed, explain the 48-hour standard, and let the customer compare contractor assessments', TRUE, 'Honest framework. Reference: Chapter 16, Module 3.', 3),
  (93, 'D', 'Decline to provide a proposal', FALSE, 'Engagement is appropriate.', 4),
  (94, 'A', 'Capitulate and write the cheaper proposal to keep the deal', FALSE, 'Capitulation damages trust.', 1),
  (94, 'B', 'Maintain the honest recommendation, offer a documented alternative if appropriate, and accept that the customer may choose a different contractor', TRUE, 'Honest discipline. Reference: Module 13, Chapter 13.', 2),
  (94, 'C', 'Lower the price on the original recommendation', FALSE, 'Price isn''t the issue if scope is right.', 3),
  (94, 'D', 'Insist the customer accept the original recommendation', FALSE, 'Pressure tactic.', 4),
  (95, 'A', 'Confirm the carrier will cover it', FALSE, 'Carrier outcomes can''t be promised.', 1),
  (95, 'B', 'Document conditions thoroughly and explain that you can''t promise carrier outcomes', TRUE, 'Standard storm-damage framing. Reference: Module 6.', 2),
  (95, 'C', 'Decline to inspect', FALSE, 'Inspection is appropriate.', 3),
  (95, 'D', 'Quote a low number to support the claim', FALSE, 'Manipulating quotes for claims is unethical.', 4),
  (96, 'A', 'Add the scope to support the claim', FALSE, 'Scope inflation is fraud.', 1),
  (96, 'B', 'Decline; explain that scope reflects what the roof needs, not what the claim might cover', TRUE, 'Honest discipline. Reference: Module 6.', 2),
  (96, 'C', 'Refer the customer elsewhere', FALSE, 'Engagement is appropriate.', 3),
  (96, 'D', 'Reduce scope to make the claim look smaller', FALSE, 'Scope reflects actual need.', 4),
  (97, 'A', 'Apologize and reduce the inspection scope', FALSE, 'Reducing scope creates problems.', 1),
  (97, 'B', 'Skip the detail inspection', FALSE, 'Details are where leaks happen.', 2),
  (97, 'C', 'Explain that details are where roofs typically leak; offer the customer the choice of a less thorough inspection but with caveats', TRUE, 'Honest response. Reference: Chapter 15.', 3),
  (97, 'D', 'Tell the customer they don''t need any work', FALSE, 'Pronouncement without inspection is dishonest.', 4),
  (98, 'A', 'Bitter exit; never engage with the customer again', FALSE, 'Damages relationship.', 1),
  (98, 'B', 'Clean exit, professional warmth, door left open for future engagement', TRUE, 'Standard pattern when customer goes elsewhere. Reference: Module 13.', 2),
  (98, 'C', 'Lower the price to match the competitor and try to keep the deal', FALSE, 'Capitulation after recommendation damages credibility.', 3),
  (98, 'D', 'Pressure the customer to reconsider', FALSE, 'Pressure tactic.', 4),
  (99, 'A', 'Continue maintenance visits indefinitely to preserve recurring revenue', FALSE, 'Maintenance on end-of-life roof is short-term spending.', 1),
  (99, 'B', 'Have the honest conversation: explain that maintenance is no longer the appropriate scope, and recommend replacement options', TRUE, 'Honest framework. Reference: Chapter 11, Module 13.', 2),
  (99, 'C', 'Drop the customer', FALSE, 'Engagement is appropriate.', 3),
  (99, 'D', 'Continue maintenance but raise the price', FALSE, 'Continuing inappropriate scope is dishonest.', 4),
  (100, 'A', 'Different based on whether the deal closes', FALSE, 'Consistency builds trust.', 1),
  (100, 'B', 'Aggressive when the deal is at risk of being lost', FALSE, 'Aggression damages relationships.', 2),
  (100, 'C', 'Consistent professional warmth and honesty regardless of outcome, recognizing that all customer interactions are deposits in the long-term relationship account', TRUE, 'Long-term relationship framework. Reference: Module 13.', 3),
  (100, 'D', 'Detached and transactional', FALSE, 'Detachment damages relationships.', 4)
) AS v(question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN quizzes q ON q.is_final_exam = TRUE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
COMMIT;
