BEGIN;
-- Chunk D: chapter quizzes (compact SELECT-FROM-VALUES form) (part 3/4)
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (1, 8, 6, 'A', 'Walking anywhere on the tiles', FALSE, NULL, 1),
  (1, 8, 6, 'B', 'Walking only on the lower third of each tile, on supported areas', TRUE, 'Standard walking technique.', 2),
  (1, 8, 6, 'C', 'Walking on dry tiles only', FALSE, NULL, 3),
  (1, 8, 6, 'D', 'Avoiding all roof contact', FALSE, NULL, 4),
  (1, 8, 7, 'A', 'Tile manufacturing defects', FALSE, NULL, 1),
  (1, 8, 7, 'B', 'Underlayment age and failure', TRUE, 'Underlayment is the waterproofing.', 2),
  (1, 8, 7, 'C', 'Storm damage to tiles only', FALSE, NULL, 3),
  (1, 8, 7, 'D', 'Customer abuse', FALSE, NULL, 4),
  (1, 8, 8, 'A', 'Full underlayment replacement', FALSE, NULL, 1),
  (1, 8, 8, 'B', 'Mortar repair within USA Flat Roof''s tile scope', TRUE, 'Localized mortar repair.', 2),
  (1, 8, 8, 'C', 'Roof replacement', FALSE, NULL, 3),
  (1, 8, 8, 'D', 'Coating', FALSE, NULL, 4),
  (1, 8, 9, 'A', 'All tiles need replacement', FALSE, NULL, 1),
  (1, 8, 9, 'B', 'Underlayment is at end of life and full re-felt is required (referred out)', TRUE, 'Underlayment age aligns.', 2),
  (1, 8, 9, 'C', 'Storm damage', FALSE, NULL, 3),
  (1, 8, 9, 'D', 'Bird damage', FALSE, NULL, 4),
  (1, 8, 10, 'A', 'Ignoring them', FALSE, NULL, 1),
  (1, 8, 10, 'B', 'Replacing the broken tiles, matching profile and color where possible', TRUE, 'Standard tile repair.', 2),
  (1, 8, 10, 'C', 'Coating over them', FALSE, NULL, 3),
  (1, 8, 10, 'D', 'Recommending full roof replacement', FALSE, NULL, 4),
  (1, 9, 1, 'A', 'Primary product offered', FALSE, NULL, 1),
  (1, 9, 1, 'B', 'Does not install new BUR; restores, recovers, or replaces existing BUR', TRUE, 'USA Flat Roof''s specific position.', 2),
  (1, 9, 1, 'C', 'Installed only on commercial', FALSE, NULL, 3),
  (1, 9, 1, 'D', 'Installed only on residential', FALSE, NULL, 4),
  (1, 9, 2, 'A', 'Welded seams', FALSE, NULL, 1),
  (1, 9, 2, 'B', 'Gravel surface or smooth asphalt cap, with multi-ply construction at edges', TRUE, 'Defining BUR features.', 2),
  (1, 9, 2, 'C', 'Granular cap sheet only', FALSE, NULL, 3),
  (1, 9, 2, 'D', 'Orange-peel texture', FALSE, NULL, 4),
  (1, 9, 3, 'A', '5–10 years', FALSE, NULL, 1),
  (1, 9, 3, 'B', '20–40+ years (legacy installs often exceed)', TRUE, 'Standard BUR lifespan.', 2),
  (1, 9, 3, 'C', 'Less than 5 years', FALSE, NULL, 3),
  (1, 9, 3, 'D', 'Lifetime guaranteed', FALSE, NULL, 4),
  (1, 9, 4, 'A', 'Aluminum / silicone / replacement', FALSE, NULL, 1),
  (1, 9, 4, 'B', 'Silicone restoration / TPO overlay / full replacement, with SPF as fourth option', TRUE, 'USA Flat Roof''s specific framework.', 2),
  (1, 9, 4, 'C', 'Patching only / overlay / replacement', FALSE, NULL, 3),
  (1, 9, 4, 'D', 'New BUR / replacement / refer out', FALSE, NULL, 4),
  (1, 9, 5, 'A', 'It determines paint color', FALSE, NULL, 1),
  (1, 9, 5, 'B', 'Multi-layer systems often disqualify recover and require tear-off', TRUE, 'Code typically permits one recover.', 2),
  (1, 9, 5, 'C', 'It affects warranty length only', FALSE, NULL, 3),
  (1, 9, 5, 'D', 'It doesn''t matter', FALSE, NULL, 4),
  (1, 9, 6, 'A', 'None special', FALSE, NULL, 1),
  (1, 9, 6, 'B', 'Asbestos potential, layer count assessment, and substrate identification', TRUE, 'Standard pre-1980s considerations.', 2),
  (1, 9, 6, 'C', 'Customer interview only', FALSE, NULL, 3),
  (1, 9, 6, 'D', 'Drone inspection required', FALSE, NULL, 4),
  (1, 9, 7, 'A', 'They never fail', FALSE, NULL, 1),
  (1, 9, 7, 'B', 'Sealant degrades over time and is a high-failure detail', TRUE, 'Pitch pan sealant is recurring maintenance.', 2),
  (1, 9, 7, 'C', 'They affect drainage', FALSE, NULL, 3),
  (1, 9, 7, 'D', 'They block ventilation', FALSE, NULL, 4),
  (1, 9, 8, 'A', 'Replacement immediately', FALSE, NULL, 1),
  (1, 9, 8, 'B', 'Restoration coating (silicone) if it qualifies, or maintenance program', TRUE, 'Mid-life single-layer with sound substrate.', 2),
  (1, 9, 8, 'C', 'Spot repair only', FALSE, NULL, 3),
  (1, 9, 8, 'D', 'Decline to inspect', FALSE, NULL, 4),
  (1, 9, 9, 'A', 'Always, on every BUR roof', FALSE, NULL, 1),
  (1, 9, 9, 'B', 'When ponding correction or insulation upgrade is the goal, after gravel removal', TRUE, 'Specific SPF use cases.', 2),
  (1, 9, 9, 'C', 'Never', FALSE, NULL, 3),
  (1, 9, 9, 'D', 'Only when customer requests it', FALSE, NULL, 4),
  (1, 9, 10, 'A', 'Quote the new BUR', FALSE, NULL, 1),
  (1, 9, 10, 'B', 'Explain USA Flat Roof doesn''t install new BUR, present alternatives, and offer to refer to a BUR specialty contractor if they prefer like-for-like', TRUE, 'Honest positioning.', 2),
  (1, 9, 10, 'C', 'Decline without explanation', FALSE, NULL, 3),
  (1, 9, 10, 'D', 'Recommend silicone restoration regardless', FALSE, NULL, 4),
  (1, 10, 1, 'A', 'Color of topcoat', FALSE, NULL, 1),
  (1, 10, 1, 'B', 'Orange-peel surface texture', TRUE, 'Most reliable SPF identifier.', 2),
  (1, 10, 1, 'C', 'Welded seams', FALSE, NULL, 3),
  (1, 10, 1, 'D', 'Granule surface', FALSE, NULL, 4),
  (1, 10, 2, 'A', 'Base sheet', FALSE, NULL, 1),
  (1, 10, 2, 'B', 'Topcoat', TRUE, 'Required for UV protection.', 2),
  (1, 10, 2, 'C', 'Cap sheet', FALSE, NULL, 3),
  (1, 10, 2, 'D', 'Flashing', FALSE, NULL, 4),
  (1, 10, 3, 'A', 'Residential, decorative, metal recover', FALSE, NULL, 1),
  (1, 10, 3, 'B', 'Ponding correction, BUR recover after gravel removal, insulation upgrade', TRUE, 'USA Flat Roof''s specific positioning.', 2),
  (1, 10, 3, 'C', 'Steep-slope shingle, parapet flashing, chimney work', FALSE, NULL, 3),
  (1, 10, 3, 'D', 'Emergency leak repair, attic ventilation, skylight installation', FALSE, NULL, 4),
  (1, 10, 4, 'A', '5 years', FALSE, NULL, 1),
  (1, 10, 4, 'B', '25+ years with topcoat maintenance', TRUE, 'Foam life depends on topcoat maintenance.', 2),
  (1, 10, 4, 'C', 'Less than 1 year', FALSE, NULL, 3),
  (1, 10, 4, 'D', 'Forever without maintenance', FALSE, NULL, 4),
  (1, 10, 5, 'A', 'Optional, every 30 years if at all', FALSE, NULL, 1),
  (1, 10, 5, 'B', 'Mandatory every 10–15 years to maintain warranty and UV protection', TRUE, 'Recoat is required, not optional.', 2),
  (1, 10, 5, 'C', 'Once at install only', FALSE, NULL, 3),
  (1, 10, 5, 'D', 'Never required', FALSE, NULL, 4),
  (1, 10, 6, 'A', 'It dissolves water', FALSE, NULL, 1),
  (1, 10, 6, 'B', 'It can be sprayed thicker in low spots and thinner near drains, creating slope during application', TRUE, 'Unique slope-correction capability.', 2),
  (1, 10, 6, 'C', 'It includes drainage piping', FALSE, NULL, 3),
  (1, 10, 6, 'D', 'It''s mechanically attached at slope', FALSE, NULL, 4),
  (1, 10, 7, 'A', 'Normal aging, no concern', FALSE, NULL, 1),
  (1, 10, 7, 'B', 'Topcoat thinning or wear; UV degradation of foam if not addressed', TRUE, 'Warning sign for foam degradation.', 2),
  (1, 10, 7, 'C', 'Improved insulation', FALSE, NULL, 3),
  (1, 10, 7, 'D', 'Manufacturer defect', FALSE, NULL, 4),
  (1, 10, 8, 'A', 'Add insulation', FALSE, NULL, 1),
  (1, 10, 8, 'B', 'Protect the SPF surface in high-traffic areas around equipment', TRUE, 'Foot traffic protection.', 2),
  (1, 10, 8, 'C', 'Drain water', FALSE, NULL, 3),
  (1, 10, 8, 'D', 'Reduce UV', FALSE, NULL, 4),
  (1, 10, 9, 'A', 'Has no consequence', FALSE, NULL, 1),
  (1, 10, 9, 'B', 'Risks warranty void and UV degradation of foam, potentially shortening system life significantly', TRUE, 'Recoat is part of warranty maintenance.', 2),
  (1, 10, 9, 'C', 'Saves money long-term', FALSE, NULL, 3),
  (1, 10, 9, 'D', 'Has no warranty implications', FALSE, NULL, 4),
  (1, 10, 10, 'A', 'Nothing else', FALSE, NULL, 1),
  (1, 10, 10, 'B', 'The alternative of replacement with tapered insulation, so customer has full picture', TRUE, 'Both real options for ponding correction.', 2),
  (1, 10, 10, 'C', 'Coating restoration', FALSE, NULL, 3),
  (1, 10, 10, 'D', 'Deferring all action', FALSE, NULL, 4)
) AS v(part_num, chap_num, question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
JOIN quizzes q ON q.chapter_id = c.id AND q.is_final_exam = FALSE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (2, 11, 1, 'A', 'An optional add-on', FALSE, NULL, 1),
  (2, 11, 1, 'B', 'The structural mechanism for long-term customer relationships', TRUE, 'Maintenance pipeline framework.', 2),
  (2, 11, 1, 'C', 'Replacement deferral only', FALSE, NULL, 3),
  (2, 11, 1, 'D', 'An emergency-only service', FALSE, NULL, 4),
  (2, 11, 2, 'A', 'Focus only above the visible damage', FALSE, NULL, 1),
  (2, 11, 2, 'B', 'Include the full roof, not just the leak area', TRUE, 'Leak-source rule.', 2),
  (2, 11, 2, 'C', 'Skip and quote a patch', FALSE, NULL, 3),
  (2, 11, 2, 'D', 'Wait for customer to identify source', FALSE, NULL, 4),
  (2, 11, 3, 'A', 'Directly above the interior damage', FALSE, NULL, 1),
  (2, 11, 3, 'B', 'Rarely directly above the interior damage; water travels along structure first', TRUE, 'Leak-source rule.', 2),
  (2, 11, 3, 'C', 'Always at the nearest penetration', FALSE, NULL, 3),
  (2, 11, 3, 'D', 'Impossible to identify', FALSE, NULL, 4),
  (2, 11, 4, 'A', 'Random bad luck', FALSE, NULL, 1),
  (2, 11, 4, 'B', 'A pattern of system aging; repair-plus-plan or replacement conversation appropriate', TRUE, 'Pattern of failure on aged roof.', 2),
  (2, 11, 4, 'C', 'Customer abuse', FALSE, NULL, 3),
  (2, 11, 4, 'D', 'Storm damage', FALSE, NULL, 4),
  (2, 11, 5, 'A', 'Roof is brand new', FALSE, NULL, 1),
  (2, 11, 5, 'B', 'Roof has localized failure but is at the older end of service or showing broader aging signs', TRUE, 'Standard repair-plus-plan trigger.', 2),
  (2, 11, 5, 'C', 'Customer wants only replacement', FALSE, NULL, 3),
  (2, 11, 5, 'D', 'Insurance is involved', FALSE, NULL, 4),
  (2, 11, 6, 'A', 'Address it anyway', FALSE, NULL, 1),
  (2, 11, 6, 'B', 'Document, escalate, and communicate the finding to the customer', TRUE, 'Standard escalation pattern.', 2),
  (2, 11, 6, 'C', 'Ignore and complete maintenance only', FALSE, NULL, 3),
  (2, 11, 6, 'D', 'Quote a price on the spot', FALSE, NULL, 4),
  (2, 11, 7, 'A', 'Continue maintenance to preserve recurring revenue', FALSE, NULL, 1),
  (2, 11, 7, 'B', 'Have the honest conversation: maintenance is no longer appropriate; recommend replacement options', TRUE, 'Honest framework.', 2),
  (2, 11, 7, 'C', 'Drop the customer', FALSE, NULL, 3),
  (2, 11, 7, 'D', 'Continue maintenance but raise price', FALSE, NULL, 4),
  (2, 11, 8, 'A', 'Should be hidden from customers', FALSE, NULL, 1),
  (2, 11, 8, 'B', 'Should be communicated transparently in advance', TRUE, 'Pricing transparency.', 2),
  (2, 11, 8, 'C', 'Don''t apply at USA Flat Roof', FALSE, NULL, 3),
  (2, 11, 8, 'D', 'Are negotiable on every call', FALSE, NULL, 4),
  (2, 11, 9, 'A', 'Patch as requested without comment', FALSE, NULL, 1),
  (2, 11, 9, 'B', 'Explain repeat repairs on aged roof are short-term spending; recommend inspection and present options', TRUE, 'Honest engagement.', 2),
  (2, 11, 9, 'C', 'Decline the work', FALSE, NULL, 3),
  (2, 11, 9, 'D', 'Recommend silicone immediately', FALSE, NULL, 4),
  (2, 11, 10, 'A', 'Capitulate and patch', FALSE, NULL, 1),
  (2, 11, 10, 'B', 'Explain repair is short-term spending; offer phased work or honest decline if budget doesn''t support replacement', TRUE, 'Honest discipline.', 2),
  (2, 11, 10, 'C', 'Insist on replacement scope', FALSE, NULL, 3),
  (2, 11, 10, 'D', 'Refer elsewhere without explanation', FALSE, NULL, 4),
  (2, 12, 1, 'A', 'Good / Fair / Poor / Failed', FALSE, NULL, 1),
  (2, 12, 1, 'B', 'Monitor / Maintenance Needed / Repair Recommended / Urgent or Escalate', TRUE, 'Standard scale.', 2),
  (2, 12, 1, 'C', 'Pass / Fail / Conditional / Re-inspect', FALSE, NULL, 3),
  (2, 12, 1, 'D', 'Green / Yellow / Red / Black', FALSE, NULL, 4),
  (2, 12, 2, 'A', 'Customer, company, and warranty system', TRUE, 'Three audiences.', 1),
  (2, 12, 2, 'B', 'Sales, production, accounting', FALSE, NULL, 2),
  (2, 12, 2, 'C', 'Customer, insurance, IRS', FALSE, NULL, 3),
  (2, 12, 2, 'D', 'Rep, customer, HOA', FALSE, NULL, 4),
  (2, 12, 3, 'A', 'Drone, photos, customer documentation, warranty documentation', TRUE, 'Four pillars from Chapter 12.', 1),
  (2, 12, 3, 'B', 'Sales, photos, pricing, certification', FALSE, NULL, 2),
  (2, 12, 3, 'C', 'Climbing, walking, photographing, leaving', FALSE, NULL, 3),
  (2, 12, 3, 'D', 'Customer interview only', FALSE, NULL, 4),
  (2, 12, 4, 'A', 'Replacing all hands-on inspection', FALSE, NULL, 1),
  (2, 12, 4, 'B', 'Multi-story buildings, tile roofs, complex geometries where walking is risky', TRUE, 'Standard drone use.', 2),
  (2, 12, 4, 'C', 'Single-family residential only', FALSE, NULL, 3),
  (2, 12, 4, 'D', 'Inspecting attics', FALSE, NULL, 4),
  (2, 12, 5, 'A', 'Skipping until rain', FALSE, NULL, 1),
  (2, 12, 5, 'B', 'Using chalk to outline extent marked by dirt rings, then photographing', TRUE, 'Standard ponding documentation.', 2),
  (2, 12, 5, 'C', 'Estimating from satellite', FALSE, NULL, 3),
  (2, 12, 5, 'D', 'Asking customer to verify', FALSE, NULL, 4),
  (2, 12, 6, 'A', 'Optional decoration', FALSE, NULL, 1),
  (2, 12, 6, 'B', 'An object included to indicate size — business card, tape measure, chalk mark', TRUE, 'Standard photo standard.', 2),
  (2, 12, 6, 'C', 'Required only on commercial', FALSE, NULL, 3),
  (2, 12, 6, 'D', 'A scale model', FALSE, NULL, 4),
  (2, 12, 7, 'A', 'Quote on the spot', FALSE, NULL, 1),
  (2, 12, 7, 'B', 'Defer to written proposal so scope and price match', TRUE, 'Honest framework.', 2),
  (2, 12, 7, 'C', 'Decline further inspection', FALSE, NULL, 3),
  (2, 12, 7, 'D', 'Quote a high anchor', FALSE, NULL, 4),
  (2, 12, 8, 'A', 'Visible roof surface conditions', FALSE, NULL, 1),
  (2, 12, 8, 'B', 'Customer-reported information (when clearly attributed)', FALSE, NULL, 2),
  (2, 12, 8, 'C', 'Severity ratings', FALSE, NULL, 3),
  (2, 12, 8, 'D', 'Structural failure, hail damage for insurance, or mold identification', TRUE, 'These exceed rep authorization.', 4),
  (2, 12, 9, 'A', 'Patch where customer points', FALSE, NULL, 1),
  (2, 12, 9, 'B', 'Escalate to senior estimator or qualified inspector; communicate honestly with customer', TRUE, 'Honest response when source unclear.', 2),
  (2, 12, 9, 'C', 'Recommend replacement', FALSE, NULL, 3),
  (2, 12, 9, 'D', 'Charge and leave', FALSE, NULL, 4),
  (2, 12, 10, 'A', 'Apologize and reduce inspection scope', FALSE, NULL, 1),
  (2, 12, 10, 'B', 'Explain documentation protects them for warranty, insurance, resale; pricing will be accurate', TRUE, 'Honest framing.', 2),
  (2, 12, 10, 'C', 'Skip documentation', FALSE, NULL, 3),
  (2, 12, 10, 'D', 'Bill for documentation time', FALSE, NULL, 4),
  (2, 13, 1, 'A', 'Adding a continuous waterproof layer', FALSE, NULL, 1),
  (2, 13, 1, 'B', 'Removing the existing roof and starting over', FALSE, NULL, 2),
  (2, 13, 1, 'C', 'Addressing a specific failure on a roof with remaining service life', TRUE, 'Standard definition.', 3),
  (2, 13, 1, 'D', 'Annual maintenance', FALSE, NULL, 4),
  (2, 13, 2, 'A', 'Targeted patching', FALSE, NULL, 1),
  (2, 13, 2, 'B', 'Adding waterproofing or service life to an aged but sound substrate', TRUE, 'Standard definition.', 2),
  (2, 13, 2, 'C', 'Tearing off the existing roof', FALSE, NULL, 3),
  (2, 13, 2, 'D', 'Roof painting', FALSE, NULL, 4),
  (2, 13, 3, 'A', 'Removing existing roof to deck', FALSE, NULL, 1),
  (2, 13, 3, 'B', 'Installing a new system over the existing one, where code permits and substrate qualifies', TRUE, 'Standard definition.', 2),
  (2, 13, 3, 'C', 'Repairing only the leaks', FALSE, NULL, 3),
  (2, 13, 3, 'D', 'Annual maintenance', FALSE, NULL, 4),
  (2, 13, 4, 'A', 'Cost, customer, condition, closing', FALSE, NULL, 1),
  (2, 13, 4, 'B', 'Condition, customer fit, budget, honest-versus-easy', TRUE, 'Four lenses in order.', 2),
  (2, 13, 4, 'C', 'Budget, condition, paperwork, warranty', FALSE, NULL, 3),
  (2, 13, 4, 'D', 'Customer, condition, customer, condition', FALSE, NULL, 4),
  (2, 13, 5, 'A', 'Light surface dirt', FALSE, NULL, 1),
  (2, 13, 5, 'B', 'Wet insulation, severe ponding, widespread substrate failure', TRUE, 'Cross-system disqualifiers.', 2),
  (2, 13, 5, 'C', 'Single failed pipe boot', FALSE, NULL, 3),
  (2, 13, 5, 'D', 'Biological staining on north slope', FALSE, NULL, 4)
) AS v(part_num, chap_num, question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
JOIN quizzes q ON q.chapter_id = c.id AND q.is_final_exam = FALSE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
COMMIT;
