BEGIN;
-- Chunk D: chapter quizzes (compact SELECT-FROM-VALUES form) (part 2/4)
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (1, 1, 1, 'A', 'Sand', FALSE, NULL, 1),
  (1, 1, 1, 'B', 'Mineral granules embedded in the asphalt', TRUE, 'Standard composition shingle definition.', 2),
  (1, 1, 1, 'C', 'Aluminum flakes', FALSE, NULL, 3),
  (1, 1, 1, 'D', 'Plastic chips', FALSE, NULL, 4),
  (1, 1, 2, 'A', 'Three-tab', FALSE, NULL, 1),
  (1, 1, 2, 'B', 'Architectural (dimensional, laminated)', TRUE, 'Industry standard since the 2000s.', 2),
  (1, 1, 2, 'C', 'Designer / luxury', FALSE, NULL, 3),
  (1, 1, 2, 'D', 'Built-up', FALSE, NULL, 4),
  (1, 1, 3, 'A', '5–10 years', FALSE, NULL, 1),
  (1, 1, 3, 'B', '18–25 years', TRUE, 'Standard NorCal field range.', 2),
  (1, 1, 3, 'C', '30–40 years', FALSE, NULL, 3),
  (1, 1, 3, 'D', '50+ years', FALSE, NULL, 4),
  (1, 1, 4, 'A', 'New roof installation', FALSE, NULL, 1),
  (1, 1, 4, 'B', 'Aging or weathering of the shingles', TRUE, 'Significant accumulation indicates aging.', 2),
  (1, 1, 4, 'C', 'Animal activity', FALSE, NULL, 3),
  (1, 1, 4, 'D', 'Insurance damage', FALSE, NULL, 4),
  (1, 1, 5, 'A', 'Causing wind damage', FALSE, NULL, 1),
  (1, 1, 5, 'B', 'Trapping heat that ages shingles from below', TRUE, 'Primary ventilation-driven aging mechanism.', 2),
  (1, 1, 5, 'C', 'Causing snow damage', FALSE, NULL, 3),
  (1, 1, 5, 'D', 'Creating algae', FALSE, NULL, 4),
  (1, 1, 6, 'A', 'The roof lasts a lifetime', FALSE, NULL, 1),
  (1, 1, 6, 'B', 'A non-prorated period followed by prorated coverage that decreases over time', TRUE, 'Honest warranty definition.', 2),
  (1, 1, 6, 'C', 'Customer can claim repair forever', FALSE, NULL, 3),
  (1, 1, 6, 'D', 'Manufacturer covers any failure', FALSE, NULL, 4),
  (1, 1, 7, 'A', 'Full replacement', FALSE, NULL, 1),
  (1, 1, 7, 'B', 'Repair of the pipe boot, with annual maintenance recommended', TRUE, 'Localized failure on roof with significant remaining life.', 2),
  (1, 1, 7, 'C', 'Silicone restoration', FALSE, NULL, 3),
  (1, 1, 7, 'D', 'Decline to inspect', FALSE, NULL, 4),
  (1, 1, 8, 'A', 'Pressure washing immediately', FALSE, NULL, 1),
  (1, 1, 8, 'B', 'Algaecide treatment with attention to underlying conditions', TRUE, 'Standard treatment without damaging shingles.', 2),
  (1, 1, 8, 'C', 'Replacement of affected area', FALSE, NULL, 3),
  (1, 1, 8, 'D', 'Painting over with roof paint', FALSE, NULL, 4),
  (1, 1, 9, 'A', 'Patching and waiting', FALSE, NULL, 1),
  (1, 1, 9, 'B', 'Fresh Roof rejuvenation', FALSE, NULL, 2),
  (1, 1, 9, 'C', 'Full replacement', TRUE, 'End-of-life condition with disqualifying issues.', 3),
  (1, 1, 9, 'D', 'Annual maintenance only', FALSE, NULL, 4),
  (1, 1, 10, 'A', 'Quote the warranty length', FALSE, NULL, 1),
  (1, 1, 10, 'B', 'Provide a range based on system, conditions, and observed condition — never a specific year-count', TRUE, 'Honest framework.', 2),
  (1, 1, 10, 'C', 'Tell them exactly 25 years', FALSE, NULL, 3),
  (1, 1, 10, 'D', 'Decline to answer', FALSE, NULL, 4),
  (1, 2, 1, 'A', 'Adhesive bonding', FALSE, NULL, 1),
  (1, 2, 1, 'B', 'Hot-air welding', TRUE, 'TPO is thermoplastic; seams are welded.', 2),
  (1, 2, 1, 'C', 'Self-adhesive tape', FALSE, NULL, 3),
  (1, 2, 1, 'D', 'Mechanical clamping', FALSE, NULL, 4),
  (1, 2, 2, 'A', '30-mil fully adhered', FALSE, NULL, 1),
  (1, 2, 2, 'B', '60-mil mechanically attached', TRUE, 'USA Flat Roof''s flagship spec.', 2),
  (1, 2, 2, 'C', '90-mil ballasted', FALSE, NULL, 3),
  (1, 2, 2, 'D', '45-mil torch-applied', FALSE, NULL, 4),
  (1, 2, 3, 'A', 'Black', FALSE, NULL, 1),
  (1, 2, 3, 'B', 'White', TRUE, 'Title 24 cool roof drives white.', 2),
  (1, 2, 3, 'C', 'Gray', FALSE, NULL, 3),
  (1, 2, 3, 'D', 'Tan', FALSE, NULL, 4),
  (1, 2, 4, 'A', 'Center of the field', FALSE, NULL, 1),
  (1, 2, 4, 'B', 'At seams, penetrations, and details', TRUE, 'Universal failure pattern.', 2),
  (1, 2, 4, 'C', 'Through the deck', FALSE, NULL, 3),
  (1, 2, 4, 'D', 'Through the parapet only', FALSE, NULL, 4),
  (1, 2, 5, 'A', 'They aren''t allowed by code', FALSE, NULL, 1),
  (1, 2, 5, 'B', 'They''re high-failure locations requiring careful welding', TRUE, 'Three-sheet meeting points are stress concentrations.', 2),
  (1, 2, 5, 'C', 'They speed installation', FALSE, NULL, 3),
  (1, 2, 5, 'D', 'They reduce warranty automatically', FALSE, NULL, 4),
  (1, 2, 6, 'A', 'Defective installation', FALSE, NULL, 1),
  (1, 2, 6, 'B', 'Normal mechanical attachment pattern', TRUE, 'Mechanical attachment shows fastener bumps; expected.', 2),
  (1, 2, 6, 'C', 'Imminent failure', FALSE, NULL, 3),
  (1, 2, 6, 'D', 'Adhered installation', FALSE, NULL, 4),
  (1, 2, 7, 'A', 'Full replacement', FALSE, NULL, 1),
  (1, 2, 7, 'B', 'Silicone restoration coating if it qualifies', TRUE, 'Mid-life with sound substrate is restoration window.', 2),
  (1, 2, 7, 'C', 'Spot repair only', FALSE, NULL, 3),
  (1, 2, 7, 'D', 'Nothing', FALSE, NULL, 4),
  (1, 2, 8, 'A', 'Manufacturing defects', FALSE, NULL, 1),
  (1, 2, 8, 'B', 'Damage from foot traffic and equipment maintenance', TRUE, 'Trade damage at HVAC is common.', 2),
  (1, 2, 8, 'C', 'UV under equipment', FALSE, NULL, 3),
  (1, 2, 8, 'D', 'Wind', FALSE, NULL, 4),
  (1, 2, 9, 'A', 'Quote TPO overlay without addressing slope', FALSE, NULL, 1),
  (1, 2, 9, 'B', 'Quote TPO with tapered insulation, or recommend SPF as alternative for ponding correction', TRUE, 'Real ponding fixes.', 2),
  (1, 2, 9, 'C', 'Apply silicone coating instead', FALSE, NULL, 3),
  (1, 2, 9, 'D', 'Decline the work', FALSE, NULL, 4),
  (1, 2, 10, 'A', 'Match the lowest price', FALSE, NULL, 1),
  (1, 2, 10, 'B', 'Help compare scopes — mil thickness, prep, fastener spec, warranty tier — not just prices', TRUE, 'Honest comparison framing.', 2),
  (1, 2, 10, 'C', 'Tell customer the cheapest is the worst', FALSE, NULL, 3),
  (1, 2, 10, 'D', 'Refuse to provide a proposal', FALSE, NULL, 4),
  (1, 3, 1, 'A', 'Roof paint', FALSE, NULL, 1),
  (1, 3, 1, 'B', 'An engineered liquid-applied membrane that bonds to the existing roof and forms a continuous waterproof layer', TRUE, 'Standard definition.', 2),
  (1, 3, 1, 'C', 'A cleaning treatment', FALSE, NULL, 3),
  (1, 3, 1, 'D', 'Wax', FALSE, NULL, 4),
  (1, 3, 2, 'A', 'Adding slope', FALSE, NULL, 1),
  (1, 3, 2, 'B', 'UV resistance and ponding water tolerance', TRUE, 'Silicone''s strengths.', 2),
  (1, 3, 2, 'C', 'Sealing leaks on disqualifying substrates', FALSE, NULL, 3),
  (1, 3, 2, 'D', 'Replacing structural elements', FALSE, NULL, 4),
  (1, 3, 3, 'A', 'The coating product, but not the substrate underneath', TRUE, 'Critical warranty point.', 1),
  (1, 3, 3, 'B', 'Coating and substrate', FALSE, NULL, 2),
  (1, 3, 3, 'C', 'Only manufacturing defects', FALSE, NULL, 3),
  (1, 3, 3, 'D', 'All leaks regardless of cause', FALSE, NULL, 4),
  (1, 3, 4, 'A', 'Light surface dirt', FALSE, NULL, 1),
  (1, 3, 4, 'B', 'Wet insulation, chronic ponding, widespread substrate failure', TRUE, 'Standard disqualifiers.', 2),
  (1, 3, 4, 'C', 'Small biological growth', FALSE, NULL, 3),
  (1, 3, 4, 'D', 'Light foot traffic', FALSE, NULL, 4),
  (1, 3, 5, 'A', 'Center of field only', FALSE, NULL, 1),
  (1, 3, 5, 'B', 'High-stress areas: seams, transitions, details', TRUE, 'Reinforcement at stress concentrations.', 2),
  (1, 3, 5, 'C', 'Entire roof surface', FALSE, NULL, 3),
  (1, 3, 5, 'D', 'Random patches', FALSE, NULL, 4)
) AS v(part_num, chap_num, question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
JOIN quizzes q ON q.chapter_id = c.id AND q.is_final_exam = FALSE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (1, 3, 6, 'A', 'Apply directly without verification', FALSE, NULL, 1),
  (1, 3, 6, 'B', 'Verify compatibility per manufacturer specifications and escalate if uncertain', TRUE, 'Standard compatibility protocol.', 2),
  (1, 3, 6, 'C', 'Remove all acrylic first', FALSE, NULL, 3),
  (1, 3, 6, 'D', 'Decline the work', FALSE, NULL, 4),
  (1, 3, 7, 'A', 'Apply the coating as requested', FALSE, NULL, 1),
  (1, 3, 7, 'B', 'Decline restoration, explain why, recommend alternatives like SPF or replacement with tapered insulation', TRUE, 'Honest decline pattern.', 2),
  (1, 3, 7, 'C', 'Apply with disclaimer', FALSE, NULL, 3),
  (1, 3, 7, 'D', 'Apply higher mil thickness', FALSE, NULL, 4),
  (1, 3, 8, 'A', '1–2 years', FALSE, NULL, 1),
  (1, 3, 8, 'B', '10–15 years', TRUE, 'Standard extension range.', 2),
  (1, 3, 8, 'C', '30+ years', FALSE, NULL, 3),
  (1, 3, 8, 'D', 'Lifetime', FALSE, NULL, 4),
  (1, 3, 9, 'A', 'Manufacturing defect', FALSE, NULL, 1),
  (1, 3, 9, 'B', 'Application over disqualifying ponding conditions', TRUE, 'Most common cause.', 2),
  (1, 3, 9, 'C', 'Customer abuse', FALSE, NULL, 3),
  (1, 3, 9, 'D', 'Normal wear', FALSE, NULL, 4),
  (1, 3, 10, 'A', 'Provide because they''re a repeat customer', FALSE, NULL, 1),
  (1, 3, 10, 'B', 'Maintain the honest decline, explain disqualification, recommend honest alternatives', TRUE, 'Honest discipline.', 2),
  (1, 3, 10, 'C', 'Apply with reduced warranty', FALSE, NULL, 3),
  (1, 3, 10, 'D', 'Refer elsewhere without explanation', FALSE, NULL, 4),
  (1, 4, 1, 'A', 'Asphalt shingle roofs', TRUE, 'Specifically for asphalt shingle.', 1),
  (1, 4, 1, 'B', 'Tile roofs', FALSE, NULL, 2),
  (1, 4, 1, 'C', 'Metal roofs', FALSE, NULL, 3),
  (1, 4, 1, 'D', 'Flat commercial', FALSE, NULL, 4),
  (1, 4, 2, 'A', 'Adding a continuous waterproof layer on the surface', FALSE, NULL, 1),
  (1, 4, 2, 'B', 'Replacing oils that aging shingles have lost', TRUE, 'Mechanism of action.', 2),
  (1, 4, 2, 'C', 'Adding granules', FALSE, NULL, 3),
  (1, 4, 2, 'D', 'Removing UV damage', FALSE, NULL, 4),
  (1, 4, 3, 'A', 'A reactive last-resort', FALSE, NULL, 1),
  (1, 4, 3, 'B', 'Proactive maintenance applied while the roof is still in good shape', TRUE, 'USA Flat Roof''s positioning.', 2),
  (1, 4, 3, 'C', 'A cosmetic-only treatment', FALSE, NULL, 3),
  (1, 4, 3, 'D', 'A leak repair product', FALSE, NULL, 4),
  (1, 4, 4, 'A', 'Looks dramatically new', FALSE, NULL, 1),
  (1, 4, 4, 'B', 'Looks largely the same as before', TRUE, 'Treatment absorbs into shingles; subtle visible change.', 2),
  (1, 4, 4, 'C', 'Becomes glossy', FALSE, NULL, 3),
  (1, 4, 4, 'D', 'Changes color completely', FALSE, NULL, 4),
  (1, 4, 5, 'A', 'Rejuvenated anyway', FALSE, NULL, 1),
  (1, 4, 5, 'B', 'Declined for rejuvenation; alternatives recommended', TRUE, 'Honest discipline.', 2),
  (1, 4, 5, 'C', 'Treated with extra application', FALSE, NULL, 3),
  (1, 4, 5, 'D', 'Coated with silicone', FALSE, NULL, 4),
  (1, 4, 6, 'A', 'A specific number based on warranty length', FALSE, NULL, 1),
  (1, 4, 6, 'B', 'The manufacturer''s published extension range with notation that actual results depend on roof condition', TRUE, 'Honest framework.', 2),
  (1, 4, 6, 'C', 'Guaranteed lifetime', FALSE, NULL, 3),
  (1, 4, 6, 'D', '30 years guaranteed', FALSE, NULL, 4),
  (1, 4, 7, 'A', 'Roof in mid-life with intact granules', FALSE, NULL, 1),
  (1, 4, 7, 'B', 'Active leaks, widespread granule loss, multiple damaged shingles, soft deck', TRUE, 'Standard disqualifiers.', 2),
  (1, 4, 7, 'C', 'North-slope algae streaking', FALSE, NULL, 3),
  (1, 4, 7, 'D', 'Recent installation alone', FALSE, NULL, 4),
  (1, 4, 8, 'A', 'Agreeing with the customer', FALSE, NULL, 1),
  (1, 4, 8, 'B', 'Acknowledging the concern, explaining the chemistry, emphasizing the qualification process', TRUE, 'Honest engagement.', 2),
  (1, 4, 8, 'C', 'Insisting it works regardless', FALSE, NULL, 3),
  (1, 4, 8, 'D', 'Refusing to engage', FALSE, NULL, 4),
  (1, 4, 9, 'A', 'Confirming this is true', FALSE, NULL, 1),
  (1, 4, 9, 'B', 'Explaining that rejuvenation extends life but doesn''t eliminate eventual replacement', TRUE, 'Honest framing.', 2),
  (1, 4, 9, 'C', 'Telling them they''ll never need replacement', FALSE, NULL, 3),
  (1, 4, 9, 'D', 'Recommending replacement immediately', FALSE, NULL, 4),
  (1, 4, 10, 'A', 'A one-time application only', FALSE, NULL, 1),
  (1, 4, 10, 'B', 'A broader maintenance program — annual inspection, gutter service, minor repairs', TRUE, 'Maintenance pipeline framework.', 2),
  (1, 4, 10, 'C', 'Insurance claim', FALSE, NULL, 3),
  (1, 4, 10, 'D', 'Replacement scope', FALSE, NULL, 4),
  (1, 5, 1, 'A', 'Adhesive bonding', FALSE, NULL, 1),
  (1, 5, 1, 'B', 'Hot-air welding', TRUE, 'Both are thermoplastics.', 2),
  (1, 5, 1, 'C', 'Self-adhesive tape', FALSE, NULL, 3),
  (1, 5, 1, 'D', 'Mechanical clamping', FALSE, NULL, 4),
  (1, 5, 2, 'A', 'Entry-level commercial', FALSE, NULL, 1),
  (1, 5, 2, 'B', 'Premium alternative to TPO with chemical and grease resistance', TRUE, 'Standard PVC positioning.', 2),
  (1, 5, 2, 'C', 'Residential product', FALSE, NULL, 3),
  (1, 5, 2, 'D', 'Coating system', FALSE, NULL, 4),
  (1, 5, 3, 'A', 'Granule loss', FALSE, NULL, 1),
  (1, 5, 3, 'B', 'Plasticizer migration leading to stiffening and brittleness', TRUE, 'Primary aging mechanism.', 2),
  (1, 5, 3, 'C', 'UV color change only', FALSE, NULL, 3),
  (1, 5, 3, 'D', 'Seam adhesive failure', FALSE, NULL, 4),
  (1, 5, 4, 'A', 'Code requires it', FALSE, NULL, 1),
  (1, 5, 4, 'B', 'PVC''s chemical and grease resistance significantly exceeds TPO', TRUE, 'Technical reason for restaurant specification.', 2),
  (1, 5, 4, 'C', 'It''s cheaper', FALSE, NULL, 3),
  (1, 5, 4, 'D', 'Required by manufacturers', FALSE, NULL, 4),
  (1, 5, 5, 'A', 'Certifying TPO based on color', FALSE, NULL, 1),
  (1, 5, 5, 'B', 'Documenting visual indicators with notation that product type cannot be certified by appearance alone', TRUE, 'Honest framework.', 2),
  (1, 5, 5, 'C', 'Skipping the identification', FALSE, NULL, 3),
  (1, 5, 5, 'D', 'Asking the customer to certify', FALSE, NULL, 4),
  (1, 5, 6, 'A', 'Brand new', FALSE, NULL, 1),
  (1, 5, 6, 'B', '15+ years old', TRUE, 'Visible on aged systems.', 2),
  (1, 5, 6, 'C', 'Less than 5 years', FALSE, NULL, 3),
  (1, 5, 6, 'D', 'Less than 10 years', FALSE, NULL, 4),
  (1, 5, 7, 'A', '5–10 years', FALSE, NULL, 1),
  (1, 5, 7, 'B', '20–30 years', TRUE, 'Standard range.', 2),
  (1, 5, 7, 'C', 'Over 50 years', FALSE, NULL, 3),
  (1, 5, 7, 'D', '1–5 years', FALSE, NULL, 4),
  (1, 5, 8, 'A', 'Silicone restoration', FALSE, NULL, 1),
  (1, 5, 8, 'B', 'Spot repair only', FALSE, NULL, 2),
  (1, 5, 8, 'C', 'Full replacement', TRUE, 'End-of-life condition.', 3),
  (1, 5, 8, 'D', 'Acrylic coating', FALSE, NULL, 4),
  (1, 5, 9, 'A', 'Direct application', FALSE, NULL, 1),
  (1, 5, 9, 'B', 'Compatibility verification per manufacturer specifications', TRUE, 'Standard protocol.', 2),
  (1, 5, 9, 'C', 'Removing all PVC first', FALSE, NULL, 3),
  (1, 5, 9, 'D', 'Refusing the work', FALSE, NULL, 4),
  (1, 5, 10, 'A', 'Recommend the cheaper one', FALSE, NULL, 1),
  (1, 5, 10, 'B', 'Help the customer understand PVC and TPO are different products with different applications and warranties — not interchangeable', TRUE, 'Honest framing.', 2),
  (1, 5, 10, 'C', 'Tell them they''re equivalent', FALSE, NULL, 3),
  (1, 5, 10, 'D', 'Refuse to compare', FALSE, NULL, 4)
) AS v(part_num, chap_num, question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
JOIN quizzes q ON q.chapter_id = c.id AND q.is_final_exam = FALSE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (1, 6, 1, 'A', 'Torch-down only', FALSE, NULL, 1),
  (1, 6, 1, 'B', 'Hot-mopped only', FALSE, NULL, 2),
  (1, 6, 1, 'C', 'Self-adhered (peel-and-stick) only', TRUE, 'Specific to USA Flat Roof.', 3),
  (1, 6, 1, 'D', 'All three methods', FALSE, NULL, 4),
  (1, 6, 2, 'A', 'Single-ply membrane', FALSE, NULL, 1),
  (1, 6, 2, 'B', 'Asphalt-based multi-ply roofing system with polymer modifiers', TRUE, 'Standard definition.', 2),
  (1, 6, 2, 'C', 'Coating', FALSE, NULL, 3),
  (1, 6, 2, 'D', 'Liquid-applied membrane', FALSE, NULL, 4),
  (1, 6, 3, 'A', 'Welded with no asphalt visible', FALSE, NULL, 1),
  (1, 6, 3, 'B', 'Cleaner than torch-down or hot-mopped — no visible asphalt squeeze-out', TRUE, 'Identification feature.', 2),
  (1, 6, 3, 'C', 'With substantial asphalt squeeze-out', FALSE, NULL, 3),
  (1, 6, 3, 'D', 'Fastener-attached', FALSE, NULL, 4),
  (1, 6, 4, 'A', 'Significantly longer service life', FALSE, NULL, 1),
  (1, 6, 4, 'B', 'Lower material cost', FALSE, NULL, 2),
  (1, 6, 4, 'C', 'No open flame during installation, eliminating fire risk', TRUE, 'Central reason for self-adhered choice.', 3),
  (1, 6, 4, 'D', 'Faster cure time', FALSE, NULL, 4),
  (1, 6, 5, 'A', 'Quote it as torch-down', FALSE, NULL, 1),
  (1, 6, 5, 'B', 'Explain USA Flat Roof installs only self-adhered, the reasoning, and offer to quote self-adhered as alternative', TRUE, 'Honest positioning.', 2),
  (1, 6, 5, 'C', 'Decline without explanation', FALSE, NULL, 3),
  (1, 6, 5, 'D', 'Propose silicone instead', FALSE, NULL, 4),
  (1, 6, 6, 'A', 'Manufacturing defects', FALSE, NULL, 1),
  (1, 6, 6, 'B', 'Trapped moisture or air, often from substrate condition', TRUE, 'Common cause.', 2),
  (1, 6, 6, 'C', 'Storm damage', FALSE, NULL, 3),
  (1, 6, 6, 'D', 'Animal damage', FALSE, NULL, 4),
  (1, 6, 7, 'A', 'May be inspected and repaired with self-adhered patches; like-for-like replacement requires escalation', TRUE, 'Standard handling.', 1),
  (1, 6, 7, 'B', 'Cannot be inspected or repaired', FALSE, NULL, 2),
  (1, 6, 7, 'C', 'Should be ignored', FALSE, NULL, 3),
  (1, 6, 7, 'D', 'Should be quoted as torch-down replacement', FALSE, NULL, 4),
  (1, 6, 8, 'A', '5 years', FALSE, NULL, 1),
  (1, 6, 8, 'B', '15–25 years', TRUE, 'Standard range.', 2),
  (1, 6, 8, 'C', '30+ years', FALSE, NULL, 3),
  (1, 6, 8, 'D', 'Lifetime', FALSE, NULL, 4),
  (1, 6, 9, 'A', 'Full replacement', FALSE, NULL, 1),
  (1, 6, 9, 'B', 'Silicone restoration if it qualifies, with longer-term replacement planning', TRUE, 'Restoration window.', 2),
  (1, 6, 9, 'C', 'Spot repair only', FALSE, NULL, 3),
  (1, 6, 9, 'D', 'Nothing', FALSE, NULL, 4),
  (1, 6, 10, 'A', 'Match the cheaper price', FALSE, NULL, 1),
  (1, 6, 10, 'B', 'Explain the methods are different products with different fire risk profiles, costs, and considerations — not equivalent', TRUE, 'Honest framing.', 2),
  (1, 6, 10, 'C', 'Tell them they''re equivalent', FALSE, NULL, 3),
  (1, 6, 10, 'D', 'Refuse to engage', FALSE, NULL, 4),
  (1, 7, 1, 'A', 'Primary restoration product', FALSE, NULL, 1),
  (1, 7, 1, 'B', 'Reference only — not typically proposed; USA Flat Roof leads with silicone', TRUE, 'Standard positioning.', 2),
  (1, 7, 1, 'C', 'Required for all flat roofs', FALSE, NULL, 3),
  (1, 7, 1, 'D', 'Equivalent to silicone', FALSE, NULL, 4),
  (1, 7, 2, 'A', 'Tolerate ponding water better', FALSE, NULL, 1),
  (1, 7, 2, 'B', 'Tolerate ponding water less well; tend to be lower cost; recoat more flexibly with other chemistries', TRUE, 'Standard comparison.', 2),
  (1, 7, 2, 'C', 'Last longer', FALSE, NULL, 3),
  (1, 7, 2, 'D', 'Require more prep', FALSE, NULL, 4),
  (1, 7, 3, 'A', 'Apply silicone directly', FALSE, NULL, 1),
  (1, 7, 3, 'B', 'Verify compatibility per manufacturer specifications and escalate any uncertainty', TRUE, 'Standard protocol.', 2),
  (1, 7, 3, 'C', 'Strip the acrylic completely first', FALSE, NULL, 3),
  (1, 7, 3, 'D', 'Decline the project', FALSE, NULL, 4),
  (1, 7, 4, 'A', 'Reliable by appearance alone', FALSE, NULL, 1),
  (1, 7, 4, 'B', 'Generally unreliable; documentation is the most accurate source', TRUE, 'Honest framework.', 2),
  (1, 7, 4, 'C', 'Color difference', FALSE, NULL, 3),
  (1, 7, 4, 'D', 'Texture difference', FALSE, NULL, 4),
  (1, 7, 5, 'A', '5–10 years', TRUE, 'Standard range.', 1),
  (1, 7, 5, 'B', '20–25 years', FALSE, NULL, 2),
  (1, 7, 5, 'C', 'Lifetime', FALSE, NULL, 3),
  (1, 7, 5, 'D', 'Less than 1 year', FALSE, NULL, 4),
  (1, 7, 6, 'A', 'Acrylic', FALSE, NULL, 1),
  (1, 7, 6, 'B', 'Silicone', TRUE, 'USA Flat Roof leads with silicone.', 2),
  (1, 7, 6, 'C', 'Polyurethane', FALSE, NULL, 3),
  (1, 7, 6, 'D', 'Bitumen-based', FALSE, NULL, 4),
  (1, 7, 7, 'A', 'Last longer than silicone', FALSE, NULL, 1),
  (1, 7, 7, 'B', 'Wear faster in ponded areas than the rest of the roof', TRUE, 'Acrylic ponding limitation.', 2),
  (1, 7, 7, 'C', 'Fix the ponding', FALSE, NULL, 3),
  (1, 7, 7, 'D', 'Prevent UV damage', FALSE, NULL, 4),
  (1, 7, 8, 'A', 'Always automatic', FALSE, NULL, 1),
  (1, 7, 8, 'B', 'Possible but requires verification per manufacturer specifications', TRUE, 'Standard protocol.', 2),
  (1, 7, 8, 'C', 'Never compatible', FALSE, NULL, 3),
  (1, 7, 8, 'D', 'Always requires complete acrylic removal', FALSE, NULL, 4),
  (1, 7, 9, 'A', 'Apply acrylic without explanation', FALSE, NULL, 1),
  (1, 7, 9, 'B', 'Explain that USA Flat Roof leads with silicone for this application; if customer specifically wants acrylic, escalate to senior estimator', TRUE, 'Honest positioning.', 2),
  (1, 7, 9, 'C', 'Refuse all coating work', FALSE, NULL, 3),
  (1, 7, 9, 'D', 'Apply silicone over their request', FALSE, NULL, 4),
  (1, 7, 10, 'A', 'A long-term restoration', FALSE, NULL, 1),
  (1, 7, 10, 'B', 'A 2–5 year life-extension product, not a true restoration', TRUE, 'Realistic positioning.', 2),
  (1, 7, 10, 'C', 'Equivalent to silicone restoration', FALSE, NULL, 3),
  (1, 7, 10, 'D', 'Required by code', FALSE, NULL, 4),
  (1, 8, 1, 'A', 'The tiles themselves', FALSE, NULL, 1),
  (1, 8, 1, 'B', 'The underlayment beneath the tiles', TRUE, 'Central tile fact.', 2),
  (1, 8, 1, 'C', 'The mortar at the ridge', FALSE, NULL, 3),
  (1, 8, 1, 'D', 'The flashings only', FALSE, NULL, 4),
  (1, 8, 2, 'A', '5–10 years', FALSE, NULL, 1),
  (1, 8, 2, 'B', '15–20 years', FALSE, NULL, 2),
  (1, 8, 2, 'C', '50+ years', TRUE, 'Standard tile lifespan.', 3),
  (1, 8, 2, 'D', 'Forever', FALSE, NULL, 4),
  (1, 8, 3, 'A', '5–10 years', FALSE, NULL, 1),
  (1, 8, 3, 'B', '20–30 years', TRUE, 'Standard underlayment lifespan.', 2),
  (1, 8, 3, 'C', '50+ years', FALSE, NULL, 3),
  (1, 8, 3, 'D', 'Forever', FALSE, NULL, 4),
  (1, 8, 4, 'A', 'Full installation including new tile installs', FALSE, NULL, 1),
  (1, 8, 4, 'B', 'Repair and maintenance only; full re-felt referred out', TRUE, 'USA Flat Roof''s specific scope.', 2),
  (1, 8, 4, 'C', 'Replacement only', FALSE, NULL, 3),
  (1, 8, 4, 'D', 'Underlayment installation only', FALSE, NULL, 4),
  (1, 8, 5, 'A', 'Profile shape', FALSE, NULL, 1),
  (1, 8, 5, 'B', 'Tap sound — concrete dull thud, clay higher-pitched ring', TRUE, 'Most reliable distinguisher.', 2),
  (1, 8, 5, 'C', 'Color always', FALSE, NULL, 3),
  (1, 8, 5, 'D', 'Cost', FALSE, NULL, 4)
) AS v(part_num, chap_num, question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
JOIN quizzes q ON q.chapter_id = c.id AND q.is_final_exam = FALSE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
COMMIT;
