BEGIN;
-- Chunk C: final exam quiz + sections + questions + answers (part 2/3)
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (21, 'A', 'Good / Fair / Poor / Failed', FALSE, 'Not the standard used in this book.', 1),
  (21, 'B', 'Monitor / Maintenance Needed / Repair Recommended / Urgent or Escalate', TRUE, 'Standard scale. Reference: Chapter 12, all system chapters.', 2),
  (21, 'C', 'Pass / Fail / Conditional / Re-inspect', FALSE, 'Not the standard used in this book.', 3),
  (21, 'D', 'Green / Yellow / Red / Black', FALSE, 'Color codes aren''t the standard rating system.', 4),
  (22, 'A', 'Customer, company, and warranty system', TRUE, 'Three audiences for documentation. Reference: Chapter 12.', 1),
  (22, 'B', 'Sales, production, and accounting', FALSE, 'These are internal departments, not the documented audiences.', 2),
  (22, 'C', 'Customer, insurance, and IRS', FALSE, 'Not the standard framing.', 3),
  (22, 'D', 'Rep, customer, and HOA', FALSE, 'Not the standard framing.', 4),
  (23, 'A', 'Optional decoration', FALSE, 'Reference scale is required for size-relevant shots.', 1),
  (23, 'B', 'An object included to indicate size — like a business card, tape measure, or chalk mark', TRUE, 'Standard photo standard. Reference: Chapter 12, Module 7.', 2),
  (23, 'C', 'Required only on commercial roofs', FALSE, 'Required across roof types when size matters.', 3),
  (23, 'D', 'A scale model of the building', FALSE, 'Not the meaning.', 4),
  (24, 'A', 'Focus only on the area above the visible damage', FALSE, 'Water travels; entry point is rarely directly above interior damage.', 1),
  (24, 'B', 'Include a full roof inspection, not just the leak area', TRUE, 'Leak-source rule. Reference: Chapter 11, Module 2.', 2),
  (24, 'C', 'Skip the inspection and quote a patch', FALSE, 'Skipping inspection causes the wrong-location patch problem.', 3),
  (24, 'D', 'Wait for the customer to identify the source', FALSE, 'Customers don''t typically identify sources; that''s the rep''s job.', 4),
  (25, 'A', 'Replacing all hands-on inspection', FALSE, 'Drones supplement, not replace, hands-on inspection.', 1),
  (25, 'B', 'Multi-story buildings, tile roofs, and complex geometries where walking is risky', TRUE, 'Drone supplements but does not replace hands-on inspection. Reference: Chapter 12, Module 7.', 2),
  (25, 'C', 'Single-family residential only', FALSE, 'Drones are valuable across building types.', 3),
  (25, 'D', 'Inspecting attics', FALSE, 'Drones don''t access attics.', 4),
  (26, 'A', 'Skipping the ponding inspection until rain', FALSE, 'Ponding evidence is documentable on dry days.', 1),
  (26, 'B', 'Using chalk to outline the extent marked by dirt rings, then photographing', TRUE, 'Standard ponding documentation. Reference: Chapter 16, Module 7.', 2),
  (26, 'C', 'Estimating the ponding from satellite photos', FALSE, 'On-roof documentation is required.', 3),
  (26, 'D', 'Asking the customer to verify', FALSE, 'Customer verification supplements but doesn''t replace direct documentation.', 4),
  (27, 'A', 'Quote the price on the spot to close the deal', FALSE, 'Verbal pricing creates anchor problems and inaccuracies.', 1),
  (27, 'B', 'Decline to inspect further until pricing is settled', FALSE, 'Inspection precedes pricing, not the reverse.', 2),
  (27, 'C', 'Defer to the written proposal so the scope and price match what''s actually on the roof', TRUE, 'Honest framework. Reference: Chapter 12, Module 11.', 3),
  (27, 'D', 'Quote a high price to anchor the negotiation', FALSE, 'Anchoring is a pressure tactic.', 4),
  (28, 'A', 'Visible roof surface conditions', FALSE, 'Reps may document visible conditions.', 1),
  (28, 'B', 'Customer-reported information (clearly attributed)', FALSE, 'Reps may document customer reports when clearly attributed.', 2),
  (28, 'C', 'Severity ratings using the four-point scale', FALSE, 'Reps apply severity ratings.', 3),
  (28, 'D', 'Structural failure, hail damage for insurance, or mold identification', TRUE, 'These exceed rep authorization. Reference: Chapter 12, Module 6.', 4),
  (29, 'A', 'Climbing the ladder', FALSE, 'Pre-inspection conversation comes first.', 1),
  (29, 'B', 'Asking lead-qualification questions before inspection', TRUE, 'Standard inspection sequence. Reference: Chapter 12.', 2),
  (29, 'C', 'Drone deployment', FALSE, 'Drone use is a method choice, not the first step.', 3),
  (29, 'D', 'Quoting a price', FALSE, 'Pricing comes after inspection and proposal preparation.', 4),
  (30, 'A', 'Sits directly above the visible interior damage', FALSE, 'Water travels along structure before showing inside.', 1),
  (30, 'B', 'Sits on the opposite side of the roof from the damage', FALSE, 'Not the typical pattern.', 2),
  (30, 'C', 'Travels along structure, conduit, or substrate before showing inside — rarely directly above interior damage', TRUE, 'Leak-source rule. Reference: Chapter 11, Module 2.', 3),
  (30, 'D', 'Cannot be identified by inspection', FALSE, 'Often identifiable through thorough inspection.', 4),
  (31, 'A', 'Walk the roof carefully despite conditions', FALSE, 'Wet or windy tile roofs are unsafe to walk.', 1),
  (31, 'B', 'Skip the inspection entirely', FALSE, 'Inspection is still possible with alternative methods.', 2),
  (31, 'C', 'Use a combination of ground-level walk-around, drone (if conditions permit), and ladder-edge — and reschedule the roof walk if conditions don''t support it', TRUE, 'Safe and thorough approach. Reference: Chapter 12.', 3),
  (31, 'D', 'Tell the customer their roof is fine', FALSE, 'Pronouncing condition without inspection is dishonest.', 4),
  (32, 'A', 'Patch the area directly above the interior damage', FALSE, 'Patching the wrong location is the textbook leak-call mistake.', 1),
  (32, 'B', 'Charge for the inspection and leave without patching', FALSE, 'Better to escalate than abandon the customer.', 2),
  (32, 'C', 'Escalate to senior estimator or qualified inspector for further investigation; communicate honestly with the customer', TRUE, 'Honest response when source can''t be identified. Reference: Module 2.', 3),
  (32, 'D', 'Recommend full replacement to be safe', FALSE, 'Recommending replacement without inspection support is overselling.', 4),
  (33, 'A', 'Address it anyway to be helpful', FALSE, 'Exceeding authorization creates problems.', 1),
  (33, 'B', 'Ignore it and complete the maintenance scope only', FALSE, 'Ignoring urgent conditions is unprofessional.', 2),
  (33, 'C', 'Document the condition, escalate, and communicate the finding to the customer', TRUE, 'Standard escalation pattern. Reference: Chapter 11, Chapter 12.', 3),
  (33, 'D', 'Quote a price on the spot', FALSE, 'Pricing follows scope, not the reverse.', 4),
  (34, 'A', 'Skip the documentation and provide a verbal price', FALSE, 'Skipping documentation creates downstream problems.', 1),
  (34, 'B', 'Explain that the documentation protects them in the future for warranty, insurance, and resale, and that the price will be accurate because the scope is real', TRUE, 'Honest framing from Module 7. Reference: Module 7, Chapter 12.', 2),
  (34, 'C', 'Apologize and reduce the inspection scope', FALSE, 'Reducing scope to placate the customer creates problems.', 3),
  (34, 'D', 'Bill the customer for the documentation time', FALSE, 'Documentation is part of standard inspection scope.', 4),
  (35, 'A', 'The coating chemistry is more important than the substrate', FALSE, 'Substrate matters more than coating chemistry for future work.', 1),
  (35, 'B', 'The substrate determines future scope options for repair, restoration, and replacement', TRUE, 'Substrate matters more than coating chemistry for future work. Reference: Chapter 17.', 2),
  (35, 'C', 'Coatings always last longer than substrates', FALSE, 'Coatings extend substrate life but the substrate is what matters.', 3),
  (35, 'D', 'The warranty depends only on the coating', FALSE, 'Warranty depends on coating but substrate matters for future scope.', 4),
  (36, 'A', 'Adding a continuous waterproof layer to an aged roof', FALSE, 'That describes restoration.', 1),
  (36, 'B', 'Removing the existing roof and installing a new one', FALSE, 'That describes replacement.', 2),
  (36, 'C', 'Addressing a specific failure on a roof that otherwise has remaining service life', TRUE, 'Standard definition. Reference: Chapter 13.', 3),
  (36, 'D', 'Annual maintenance work', FALSE, 'Maintenance is broader than repair.', 4),
  (37, 'A', 'Targeted patching of a single failure', FALSE, 'That describes repair.', 1),
  (37, 'B', 'Adding waterproofing, performance, or service life to an aged but sound substrate', TRUE, 'Standard definition. Reference: Chapter 13.', 2),
  (37, 'C', 'Tearing off the existing roof and starting over', FALSE, 'That describes replacement.', 3),
  (37, 'D', 'The same as roof painting', FALSE, 'Coatings aren''t paint.', 4),
  (38, 'A', 'Removing the existing roof down to the deck', FALSE, 'That describes tear-off.', 1),
  (38, 'B', 'Installing a new roof system over the existing one, where code permits and the substrate qualifies', TRUE, 'Standard definition. Reference: Chapter 13.', 2),
  (38, 'C', 'Repairing only the leaks', FALSE, 'That describes repair.', 3),
  (38, 'D', 'Annual maintenance', FALSE, 'Maintenance isn''t recover.', 4),
  (39, 'A', 'Light surface dirt', FALSE, 'Surface dirt is addressable through prep.', 1),
  (39, 'B', 'Wet insulation, severe ponding, or widespread substrate failure', TRUE, 'Cross-system disqualifiers. Reference: Chapter 13, Table 6.', 2),
  (39, 'C', 'A single failed pipe boot', FALSE, 'Localized failures are addressable in prep.', 3),
  (39, 'D', 'Biological staining on the north slope', FALSE, 'Treatable; not disqualifying.', 4),
  (40, 'A', 'Cost, customer, condition, closing', FALSE, 'Not the standard framework.', 1),
  (40, 'B', 'Condition, customer fit, budget, honest-versus-easy', TRUE, 'Four lenses in order. Reference: Chapter 13.', 2),
  (40, 'C', 'Budget, condition, paperwork, warranty', FALSE, 'Not the standard framework.', 3),
  (40, 'D', 'Customer, condition, customer, condition', FALSE, 'Not the standard framework.', 4)
) AS v(question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN quizzes q ON q.is_final_exam = TRUE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (41, 'A', 'Write the replacement proposal — the customer asked for it', FALSE, 'Overselling on a roof that doesn''t need replacement is dishonest.', 1),
  (41, 'B', 'Explain that the roof has significant remaining life and recommend repair or maintenance instead', TRUE, 'Honest answer when customer wants more than the roof needs. Reference: Chapter 13, Module 9.', 2),
  (41, 'C', 'Recommend silicone restoration as a compromise', FALSE, 'Restoration on a young roof is also overselling.', 3),
  (41, 'D', 'Refer the customer elsewhere', FALSE, 'Honest engagement preferred over deflection.', 4),
  (42, 'A', 'Provide the proposal because they''re a repeat customer', FALSE, 'Long-term relationship is the reason to hold the line, not capitulate.', 1),
  (42, 'B', 'Provide the proposal but with a higher-tier product', FALSE, 'Higher-tier product on disqualified substrate still doesn''t perform.', 2),
  (42, 'C', 'Decline to propose restoration, explain why, and recommend an honest alternative', TRUE, 'Honest-versus-easy moment. Reference: Chapters 3, 13, Module 13.', 3),
  (42, 'D', 'Refer them to a different contractor without explanation', FALSE, 'Explanation is part of honest engagement.', 4),
  (43, 'A', 'The roof is brand new', FALSE, 'Brand new roofs don''t need plans for replacement.', 1),
  (43, 'B', 'The roof has a localized failure but is also at the older end of its service range or showing broader aging signs', TRUE, 'Definition of repair-plus-plan. Reference: Chapter 11, Module 9.', 2),
  (43, 'C', 'The customer wants only replacement', FALSE, 'Repair-plus-plan addresses cases where customer hasn''t requested replacement.', 3),
  (43, 'D', 'Insurance is involved', FALSE, 'Insurance involvement is a separate conversation.', 4),
  (44, 'A', 'Full replacement', FALSE, 'Replacement on young roof with localized failure is overselling.', 1),
  (44, 'B', 'Silicone restoration coating', FALSE, 'Restoration is more than localized failure requires.', 2),
  (44, 'C', 'Targeted repair of the puncture, with annual maintenance recommended', TRUE, 'Young roof with localized failure. Reference: Chapter 2, Chapter 13.', 3),
  (44, 'D', 'Decline to inspect', FALSE, 'Inspection is the rep''s job.', 4),
  (45, 'A', 'Full replacement immediately', FALSE, 'Aged but serviceable roof doesn''t need immediate replacement.', 1),
  (45, 'B', 'Spot repair only', FALSE, 'Mid-life roof with broader aging signs benefits from restoration.', 2),
  (45, 'C', 'Silicone coating restoration if the substrate qualifies, with a longer-term replacement plan', TRUE, 'Mid-life roof with sound substrate. Reference: Chapter 6.', 3),
  (45, 'D', 'Decline to inspect further', FALSE, 'Inspection is required for recommendation.', 4),
  (46, 'A', 'Aluminum coating / silicone / TPO overlay', FALSE, 'Aluminum isn''t part of USA Flat Roof''s framework.', 1),
  (46, 'B', 'Silicone restoration / TPO overlay / full replacement (with SPF as a fourth option for specific use cases)', TRUE, 'USA Flat Roof''s specific framework. Reference: Chapter 9.', 2),
  (46, 'C', 'Patching only / overlay / replacement', FALSE, 'Doesn''t reflect USA Flat Roof''s specific framework.', 3),
  (46, 'D', 'Modified bitumen overlay / new BUR / replacement', FALSE, 'USA Flat Roof doesn''t install new BUR.', 4),
  (47, 'A', 'Silicone coating restoration', FALSE, 'End-of-life conditions disqualify restoration.', 1),
  (47, 'B', 'Spot repair the cracked areas', FALSE, 'Widespread aging means localized repair won''t address the system.', 2),
  (47, 'C', 'Full replacement', TRUE, 'End-of-life PVC with chronic ponding. Reference: Chapter 5.', 3),
  (47, 'D', 'Acrylic coating to restore flexibility', FALSE, 'Coatings don''t restore flexibility to aged PVC.', 4),
  (48, 'A', 'Silicone restoration coating only', FALSE, 'Coatings don''t fix ponding.', 1),
  (48, 'B', 'SPF (with taper) or replacement with tapered insulation; both address the slope, neither is cheapest by total cost but both actually solve the problem', TRUE, 'Both address slope. Reference: Chapter 16.', 2),
  (48, 'C', 'Add another drain anywhere on the roof', FALSE, 'Drain placement requires engineering analysis.', 3),
  (48, 'D', 'Apply two coats of acrylic coating', FALSE, 'Coatings don''t fix ponding.', 4),
  (49, 'A', 'Apply the rejuvenation as requested', FALSE, 'Outside qualifying window; rejuvenation won''t perform.', 1),
  (49, 'B', 'Apply rejuvenation but with a higher application rate', FALSE, 'Application rate doesn''t fix qualifying-window issues.', 2),
  (49, 'C', 'Decline to propose rejuvenation, explain why the roof does not qualify, and recommend an honest alternative', TRUE, 'End-of-life shingle outside qualifying window. Reference: Chapter 4, Module 5.', 3),
  (49, 'D', 'Offer rejuvenation only if the customer signs a waiver', FALSE, 'Waivers don''t make a non-qualifying roof qualify.', 4),
  (50, 'A', 'Quote the project as torch-down to capture the work', FALSE, 'USA Flat Roof installs only self-adhered.', 1),
  (50, 'B', 'Explain that USA Flat Roof installs only self-adhered modified bitumen, the reasoning, and offer to quote self-adhered as an alternative', TRUE, 'Honest positioning. Reference: Chapter 6.', 2),
  (50, 'C', 'Decline the project without explanation', FALSE, 'Explanation is part of honest engagement.', 3),
  (50, 'D', 'Propose silicone coating instead', FALSE, 'Silicone isn''t a replacement for new modified bitumen.', 4),
  (51, 'A', 'A specific number of years based on warranty length', FALSE, 'Warranty length isn''t service life.', 1),
  (51, 'B', 'A range based on system, conditions, and observed condition — never a specific year-count', TRUE, 'Honest framework. Reference: Module 1, all system chapters.', 2),
  (51, 'C', 'A guarantee', FALSE, 'Reps don''t guarantee specific lifespans.', 3),
  (51, 'D', 'A non-answer', FALSE, 'Customers deserve a substantive answer.', 4),
  (52, 'A', 'Always directly above the interior damage', FALSE, 'Water travels along structure first.', 1),
  (52, 'B', 'Rarely directly above the interior damage; water travels before showing inside', TRUE, 'Leak-source rule. Reference: Chapter 11, Module 2.', 2),
  (52, 'C', 'Impossible to identify', FALSE, 'Often identifiable through inspection.', 3),
  (52, 'D', 'Always at the nearest penetration', FALSE, 'Penetrations are common but not always the source.', 4),
  (53, 'A', 'The roof itself lasts a lifetime', FALSE, 'Warranty length doesn''t equal service life.', 1),
  (53, 'B', 'A non-prorated period followed by prorated coverage that decreases over time, with significant exclusions throughout', TRUE, 'Honest definition. Reference: Chapter 1, Module 12.', 2),
  (53, 'C', 'The customer can claim repair forever', FALSE, 'Coverage decreases over time.', 3),
  (53, 'D', 'The manufacturer covers any failure', FALSE, 'Significant exclusions apply.', 4),
  (54, 'A', '''Yes, definitely''', FALSE, 'Coverage requires document review.', 1),
  (54, 'B', '''No, never''', FALSE, 'Coverage requires document review.', 2),
  (54, 'C', 'Walk through the layered warranty structure (manufacturer material, manufacturer system, contractor workmanship) and review the specific document', TRUE, 'Honest response. Reference: Module 12.', 3),
  (54, 'D', '''I''ll check with the manufacturer and call you back''', FALSE, 'Document review is part of the conversation, not deferral.', 4),
  (55, 'A', 'Given a verbal price to close the deal', FALSE, 'Verbal pricing creates problems.', 1),
  (55, 'B', 'Told the price will come in the written proposal so the scope and price match', TRUE, 'Honest framework. Reference: Module 11.', 2),
  (55, 'C', 'Refused further inspection', FALSE, 'Inspection continues regardless of pricing pressure.', 3),
  (55, 'D', 'Quoted a high anchor', FALSE, 'Anchoring is a pressure tactic.', 4),
  (56, 'A', 'Recommend the cheapest option regardless of fit', FALSE, 'Cheapest option may not perform.', 1),
  (56, 'B', 'Confirm that the cheapest option performs for their roof; if it doesn''t, name that and offer alternatives', TRUE, 'Honest engagement. Reference: Module 11, Chapter 13.', 2),
  (56, 'C', 'Decline the project', FALSE, 'Engagement is appropriate.', 3),
  (56, 'D', 'Pressure the customer toward a higher-cost option', FALSE, 'Pressure tactics damage trust.', 4),
  (57, 'A', 'Sell the most expensive option since it''s requested', FALSE, 'Overselling on a roof that doesn''t need it is dishonest.', 1),
  (57, 'B', 'Recommend what the roof actually needs, not the most expensive option', TRUE, 'Don''t upsell. Reference: Module 11, Chapter 13.', 2),
  (57, 'C', 'Add unnecessary scope to justify a higher price', FALSE, 'Scope inflation is dishonest.', 3),
  (57, 'D', 'Refer the customer elsewhere', FALSE, 'Engagement is appropriate.', 4),
  (58, 'A', 'Defer to the customer''s report', FALSE, 'Observations supplement reports.', 1),
  (58, 'B', 'Tell the customer they''re wrong', FALSE, 'Confrontational framing damages trust.', 2),
  (58, 'C', 'Document what was observed, ask for documentation, and reconcile any discrepancy honestly', TRUE, 'Honest framework. Reference: Chapter 17, Chapter 18.', 3),
  (58, 'D', 'Quote work based on the customer''s report', FALSE, 'Quoting on unverified information creates problems.', 4),
  (59, 'A', 'Confirm the other contractor is correct', FALSE, 'Coverage isn''t unlimited.', 1),
  (59, 'B', 'Bash the other contractor', FALSE, 'Bashing competitors is unprofessional.', 2),
  (59, 'C', 'Don''t bash the contractor; explain what warranties typically actually cover', TRUE, 'Honest framing. Reference: Module 12.', 3),
  (59, 'D', 'Recommend full replacement to avoid the issue', FALSE, 'Replacement isn''t always the right scope.', 4),
  (60, 'A', '24 hours after rain stops', FALSE, 'Industry standard is 48 hours.', 1),
  (60, 'B', '48 hours after rain stops', TRUE, 'Industry standard. Reference: Chapter 16, Module 3.', 2),
  (60, 'C', 'One week after rain stops', FALSE, 'One week is too long.', 3),
  (60, 'D', 'There is no standard', FALSE, 'Standard exists.', 4)
) AS v(question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN quizzes q ON q.is_final_exam = TRUE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
COMMIT;
