BEGIN;
-- Chunk B: sections (compact SELECT-FROM-VALUES form) (part 2/2)
INSERT INTO sections (chapter_id, section_number, title, content_markdown, is_instructor_only, display_order)
SELECT c.id, v.section_number, v.title, '', v.is_instructor_only, v.display_order
FROM (VALUES
  (2, 16, '23', 'Instructor Notes', TRUE, 23),
  (2, 16, '24', 'Key Terms to Remember', FALSE, 24),
  (2, 16, '25', 'Chapter Summary', FALSE, 25),
  (2, 16, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (2, 16, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (2, 17, '1', 'Learning Objectives', FALSE, 1),
  (2, 17, '2', 'What This System Is', FALSE, 2),
  (2, 17, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (2, 17, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (2, 17, '5', 'Inspection Process', FALSE, 5),
  (2, 17, '6', 'Common Failure Points', FALSE, 6),
  (2, 17, '7', 'Severity Rating Reference', FALSE, 7),
  (2, 17, '8', 'Maintenance Patterns', FALSE, 8),
  (2, 17, '9', 'Repair Approach', FALSE, 9),
  (2, 17, '10', 'Restoration Approach', FALSE, 10),
  (2, 17, '11', 'Replacement Approach', FALSE, 11),
  (2, 17, '12', 'Recommendation Decision Framework', FALSE, 12),
  (2, 17, '13', 'Disqualifying Conditions', FALSE, 13),
  (2, 17, '14', 'Sales Conversation Guide', FALSE, 14),
  (2, 17, '15', 'Lead Qualification Questions', FALSE, 15),
  (2, 17, '16', 'Customer Objection Handling', FALSE, 16),
  (2, 17, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (2, 17, '18', 'Common Sales Mistakes', FALSE, 18),
  (2, 17, '19', 'Warranty Reality', FALSE, 19),
  (2, 17, '20', 'Pricing Conversation Notes', FALSE, 20),
  (2, 17, '21', 'When to Escalate', FALSE, 21),
  (2, 17, '22', 'Company Method Box', FALSE, 22),
  (2, 17, '23', 'Instructor Notes', TRUE, 23),
  (2, 17, '24', 'Key Terms to Remember', FALSE, 24),
  (2, 17, '25', 'Chapter Summary', FALSE, 25),
  (2, 17, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (2, 17, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (2, 18, '1', 'Learning Objectives', FALSE, 1),
  (2, 18, '2', 'What This System Is', FALSE, 2),
  (2, 18, '3', 'Where USA Flat Roof Uses It', FALSE, 3),
  (2, 18, '4', 'Recognition - How to Identify on Sight', FALSE, 4),
  (2, 18, '5', 'Inspection Process', FALSE, 5),
  (2, 18, '6', 'Common Failure Points', FALSE, 6),
  (2, 18, '7', 'Severity Rating Reference', FALSE, 7),
  (2, 18, '8', 'Maintenance Patterns', FALSE, 8),
  (2, 18, '9', 'Repair Approach', FALSE, 9),
  (2, 18, '10', 'Restoration Approach', FALSE, 10),
  (2, 18, '11', 'Replacement Approach', FALSE, 11),
  (2, 18, '12', 'Recommendation Decision Framework', FALSE, 12),
  (2, 18, '13', 'Disqualifying Conditions', FALSE, 13),
  (2, 18, '14', 'Sales Conversation Guide', FALSE, 14),
  (2, 18, '15', 'Lead Qualification Questions', FALSE, 15),
  (2, 18, '16', 'Customer Objection Handling', FALSE, 16),
  (2, 18, '17', 'Honest-Versus-Easy Moments', FALSE, 17),
  (2, 18, '18', 'Common Sales Mistakes', FALSE, 18),
  (2, 18, '19', 'Warranty Reality', FALSE, 19),
  (2, 18, '20', 'Pricing Conversation Notes', FALSE, 20),
  (2, 18, '21', 'When to Escalate', FALSE, 21),
  (2, 18, '22', 'Company Method Box', FALSE, 22),
  (2, 18, '23', 'Instructor Notes', TRUE, 23),
  (2, 18, '24', 'Key Terms to Remember', FALSE, 24),
  (2, 18, '25', 'Chapter Summary', FALSE, 25),
  (2, 18, '26', 'End-of-Chapter Quiz', FALSE, 26),
  (2, 18, '27', 'Manager Review Checklist + Verification Notes', TRUE, 27),
  (3, 1, '1', 'Learning Objectives', FALSE, 1),
  (3, 1, '2', 'Core Content', FALSE, 2),
  (3, 1, '3', 'Examples', FALSE, 3),
  (3, 1, '4', 'Common Mistakes', FALSE, 4),
  (3, 1, '5', 'Quick Reference Summary', FALSE, 5),
  (3, 2, '1', 'Learning Objectives', FALSE, 1),
  (3, 2, '2', 'Core Content', FALSE, 2),
  (3, 2, '3', 'Examples', FALSE, 3),
  (3, 2, '4', 'Common Mistakes', FALSE, 4),
  (3, 2, '5', 'Quick Reference Summary', FALSE, 5),
  (3, 3, '1', 'Learning Objectives', FALSE, 1),
  (3, 3, '2', 'Core Content', FALSE, 2),
  (3, 3, '3', 'Examples', FALSE, 3),
  (3, 3, '4', 'Common Mistakes', FALSE, 4),
  (3, 3, '5', 'Quick Reference Summary', FALSE, 5),
  (3, 4, '1', 'Learning Objectives', FALSE, 1),
  (3, 4, '2', 'Core Content', FALSE, 2),
  (3, 4, '3', 'Examples', FALSE, 3),
  (3, 4, '4', 'Common Mistakes', FALSE, 4),
  (3, 4, '5', 'Quick Reference Summary', FALSE, 5),
  (3, 5, '1', 'Learning Objectives', FALSE, 1),
  (3, 5, '2', 'Core Content', FALSE, 2),
  (3, 5, '3', 'Examples', FALSE, 3),
  (3, 5, '4', 'Common Mistakes', FALSE, 4),
  (3, 5, '5', 'Quick Reference Summary', FALSE, 5),
  (3, 6, '1', 'Learning Objectives', FALSE, 1),
  (3, 6, '2', 'Core Content', FALSE, 2),
  (3, 6, '3', 'Examples', FALSE, 3),
  (3, 6, '4', 'Common Mistakes', FALSE, 4),
  (3, 6, '5', 'Quick Reference Summary', FALSE, 5),
  (3, 7, '1', 'Learning Objectives', FALSE, 1),
  (3, 7, '2', 'Core Content', FALSE, 2),
  (3, 7, '3', 'Examples', FALSE, 3),
  (3, 7, '4', 'Common Mistakes', FALSE, 4),
  (3, 7, '5', 'Quick Reference Summary', FALSE, 5),
  (3, 8, '1', 'Learning Objectives', FALSE, 1),
  (3, 8, '2', 'Core Content', FALSE, 2),
  (3, 8, '3', 'Examples', FALSE, 3),
  (3, 8, '4', 'Common Mistakes', FALSE, 4),
  (3, 8, '5', 'Quick Reference Summary', FALSE, 5),
  (3, 9, '1', 'Learning Objectives', FALSE, 1)
) AS v(part_num, chap_num, section_number, title, is_instructor_only, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
ON CONFLICT (chapter_id, section_number) DO NOTHING;
INSERT INTO sections (chapter_id, section_number, title, content_markdown, is_instructor_only, display_order)
SELECT c.id, v.section_number, v.title, '', v.is_instructor_only, v.display_order
FROM (VALUES
  (3, 9, '2', 'Core Content', FALSE, 2),
  (3, 9, '3', 'Examples', FALSE, 3),
  (3, 9, '4', 'Common Mistakes', FALSE, 4),
  (3, 9, '5', 'Quick Reference Summary', FALSE, 5),
  (3, 10, '1', 'Learning Objectives', FALSE, 1),
  (3, 10, '2', 'Core Content', FALSE, 2),
  (3, 10, '3', 'Examples', FALSE, 3),
  (3, 10, '4', 'Common Mistakes', FALSE, 4),
  (3, 10, '5', 'Quick Reference Summary', FALSE, 5),
  (3, 11, '1', 'Learning Objectives', FALSE, 1),
  (3, 11, '2', 'Core Content', FALSE, 2),
  (3, 11, '3', 'Examples', FALSE, 3),
  (3, 11, '4', 'Common Mistakes', FALSE, 4),
  (3, 11, '5', 'Quick Reference Summary', FALSE, 5),
  (3, 12, '1', 'Learning Objectives', FALSE, 1),
  (3, 12, '2', 'Core Content', FALSE, 2),
  (3, 12, '3', 'Examples', FALSE, 3),
  (3, 12, '4', 'Common Mistakes', FALSE, 4),
  (3, 12, '5', 'Quick Reference Summary', FALSE, 5),
  (3, 13, '1', 'Learning Objectives', FALSE, 1),
  (3, 13, '2', 'Core Content', FALSE, 2),
  (3, 13, '3', 'Examples', FALSE, 3),
  (3, 13, '4', 'Common Mistakes', FALSE, 4),
  (3, 13, '5', 'Quick Reference Summary', FALSE, 5)
) AS v(part_num, chap_num, section_number, title, is_instructor_only, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
ON CONFLICT (chapter_id, section_number) DO NOTHING;
COMMIT;
