BEGIN;
-- Chunk C: final exam quiz + sections + questions + answers (part 1/3)
INSERT INTO quizzes (chapter_id, title, passing_score_percent, question_count, is_final_exam, retake_cooldown_hours, allow_section_review)
VALUES ((SELECT c.id FROM chapters c JOIN book_parts p ON c.part_id = p.id WHERE p.part_number = 7 AND c.chapter_number = 1), 'Final Comprehensive Exam', 80, 100, TRUE, 24, TRUE)
ON CONFLICT (chapter_id) DO UPDATE SET
  title = EXCLUDED.title,
  passing_score_percent = EXCLUDED.passing_score_percent,
  question_count = EXCLUDED.question_count,
  is_final_exam = EXCLUDED.is_final_exam,
  retake_cooldown_hours = EXCLUDED.retake_cooldown_hours,
  allow_section_review = EXCLUDED.allow_section_review;
INSERT INTO quiz_sections (quiz_id, section_number, title, question_count, display_order)
SELECT q.id, v.section_number, v.title, v.question_count, v.section_number
FROM (VALUES
  (1, 'System Identification and Recognition', 20),
  (2, 'Inspection Skills', 15),
  (3, 'Repair vs Restoration vs Replacement', 15),
  (4, 'Customer Communication', 15),
  (5, 'System-Specific Knowledge', 15),
  (6, 'Comparisons and Cross-System Reasoning', 10),
  (7, 'Objection Handling and Honest-Versus-Easy Scenarios', 10)
) AS v(section_number, title, question_count)
JOIN quizzes q ON q.is_final_exam = TRUE
ON CONFLICT ON CONSTRAINT quiz_sections_quiz_id_section_number_key DO UPDATE SET
  title = EXCLUDED.title,
  question_count = EXCLUDED.question_count,
  display_order = EXCLUDED.display_order;
INSERT INTO quiz_questions (quiz_id, quiz_section_id, question_number, question_text, difficulty, display_order)
SELECT q.id, qs.id, v.question_number, v.question_text, v.difficulty, v.question_number
FROM (VALUES
  (1, 1, 'A flat commercial roof with characteristic orange-peel surface texture is most likely:', 'beginner'),
  (1, 2, 'A black single-ply commercial roof with glued or taped seams is most likely:', 'beginner'),
  (1, 3, 'The most reliable single indicator that a residential roof is composition shingle is:', 'beginner'),
  (1, 4, 'A commercial flat roof with embedded gravel surface and visible multi-ply construction at edges is most likely:', 'beginner'),
  (1, 5, 'What does ''TPO'' stand for?', 'beginner'),
  (1, 6, 'What does ''PVC'' stand for in roofing?', 'beginner'),
  (1, 7, '''60-mil'' in TPO membrane specifications refers to:', 'beginner'),
  (1, 8, 'A composition shingle with two layers bonded together creating a shadowed, textured appearance is:', 'beginner'),
  (1, 9, 'The primary distinguishing visual feature between TPO and PVC is:', 'beginner'),
  (1, 10, 'Concrete tile and clay tile differ most reliably in:', 'beginner'),
  (1, 11, 'The first step in the four-step decision tree for commercial flat-roof identification is:', 'intermediate'),
  (1, 12, 'A 1968 commercial building has a white-coated flat roof. What inspection priorities does the building age create?', 'intermediate'),
  (1, 13, 'A restaurant building with significant kitchen exhaust shows a white welded-seam membrane that has held up well around grease vents. The system is most likely:', 'intermediate'),
  (1, 14, 'A heavily coated commercial roof requires what additional inspection priority beyond surface evaluation?', 'intermediate'),
  (1, 15, 'A 1995 NorCal tract home has a red barrel-profile roof. The most likely system is:', 'intermediate'),
  (1, 16, 'A homeowner says they have ''wood shake.'' The pieces look like wood but tap with a plastic pop. The most likely system is:', 'intermediate'),
  (1, 17, 'A commercial flat roof has a continuous painted-looking surface with visible brush texture and no visible welded seams or fastener rows. The most likely system is:', 'intermediate'),
  (1, 18, 'A rep is asked to confirm whether a roof is TPO or PVC. There is no documentation. The most appropriate response is:', 'advanced'),
  (1, 19, 'A roof has pitched composition shingle on the main roof and a flat-roof section over a rear addition. The flat section requires:', 'advanced'),
  (1, 20, 'A homeowner says they have ''real slate.'' On inspection, the pieces are uniform manufactured color, light weight, and tap with a plastic pop. The most appropriate response is:', 'advanced'),
  (2, 21, 'The four-point Inspection Severity Scale used throughout this book is:', 'beginner'),
  (2, 22, 'The three audiences for inspection documentation are:', 'beginner'),
  (2, 23, 'A reference scale in a damage photo is:', 'beginner'),
  (2, 24, 'When a customer reports an interior leak, the inspection should:', 'beginner'),
  (2, 25, 'Drone inspection is most valuable for:', 'intermediate'),
  (2, 26, 'Documenting ponding evidence on a dry-day inspection requires:', 'intermediate'),
  (2, 27, 'A customer asks for a verbal price during the inspection. The most appropriate response is:', 'intermediate'),
  (2, 28, 'Which of the following may a sales rep NOT document or certify in an inspection report?', 'intermediate'),
  (2, 29, 'The first step in the inspection sequence is:', 'intermediate'),
  (2, 30, '''Leak entry point'' on a roof typically:', 'intermediate'),
  (2, 31, 'A rep arrives at a steep-slope tile roof on a windy day. The customer wants a thorough inspection. The most appropriate approach is:', 'advanced'),
  (2, 32, 'A rep arrives at a leak repair call and cannot identify the leak source after a full inspection. The most appropriate next step is:', 'advanced'),
  (2, 33, 'A maintenance call reveals an Urgent severity condition the rep is not authorized to address. The most appropriate response is:', 'advanced'),
  (2, 34, 'A customer says ''you''re documenting too much — I just want a price.'' The most honest response is:', 'advanced'),
  (2, 35, 'Substrate identification on a heavily coated commercial roof matters most because:', 'advanced'),
  (3, 36, '''Repair'' in the four-scope framework is best described as:', 'beginner'),
  (3, 37, '''Restoration'' in the four-scope framework is best described as:', 'beginner'),
  (3, 38, '''Recover (overlay)'' is best described as:', 'beginner'),
  (3, 39, 'Which of the following is a disqualifying condition for restoration across most systems?', 'beginner'),
  (3, 40, 'The four decision lenses for recommendations, in order, are:', 'beginner'),
  (3, 41, 'A customer with a 6-year-old roof in good condition asks for replacement. The most appropriate response is:', 'intermediate'),
  (3, 42, 'A repeat customer asks for restoration on a roof the rep believes does not qualify. The most appropriate response is:', 'intermediate'),
  (3, 43, 'The ''repair-plus-plan'' conversation is appropriate when:', 'intermediate'),
  (3, 44, 'A 12-year-old TPO roof has a single punctured area and is otherwise in excellent condition. The most appropriate recommendation is:', 'intermediate'),
  (3, 45, 'A 17-year-old two-ply self-adhered modified bitumen roof has light surface wear, intact seams, light ponding in two spots, and adequate granule coverage. The most appropriate recommendation is:', 'intermediate'),
  (3, 46, 'USA Flat Roof''s recommendation framework on a single-layer BUR is:', 'intermediate'),
  (3, 47, 'A 28-year-old PVC roof shows widespread membrane stiffening, multiple cracked areas, and chronic ponding. The most honest recommendation is:', 'intermediate'),
  (3, 48, 'A property manager wants the cheapest option to address chronic ponding on a flat commercial roof. The honest options on the table are:', 'advanced'),
  (3, 49, 'A homeowner with a 23-year-old three-tab roof, widespread granule loss, and active leaks wants Fresh Roof rejuvenation. The most appropriate response is:', 'advanced'),
  (3, 50, 'A property owner asks USA Flat Roof to torch-down a replacement modified bitumen roof. The most appropriate response is:', 'advanced')
) AS v(section_number, question_number, question_text, difficulty)
JOIN quizzes q ON q.is_final_exam = TRUE
JOIN quiz_sections qs ON qs.quiz_id = q.id AND qs.section_number = v.section_number
ON CONFLICT ON CONSTRAINT quiz_questions_quiz_id_question_number_key DO UPDATE SET
  quiz_section_id = EXCLUDED.quiz_section_id,
  question_text = EXCLUDED.question_text,
  difficulty = EXCLUDED.difficulty,
  display_order = EXCLUDED.display_order;
INSERT INTO quiz_questions (quiz_id, quiz_section_id, question_number, question_text, difficulty, display_order)
SELECT q.id, qs.id, v.question_number, v.question_text, v.difficulty, v.question_number
FROM (VALUES
  (4, 51, 'The most accurate response to a customer asking ''how long will this roof last?'' includes:', 'beginner'),
  (4, 52, 'When a customer reports a ceiling leak, the entry point on the roof is:', 'beginner'),
  (4, 53, '''Lifetime warranty'' on shingles typically means:', 'beginner'),
  (4, 54, 'When a customer asks ''is this covered under warranty?'', the most accurate response is:', 'beginner'),
  (4, 55, 'A customer who insists on a verbal price during inspection should be:', 'beginner'),
  (4, 56, 'A customer says ''I want the cheapest option.'' The most honest rep response is:', 'intermediate'),
  (4, 57, 'A customer says ''money is no object — give me the most expensive option.'' The most appropriate response is:', 'intermediate'),
  (4, 58, 'When a customer reports their roof system as something different from what the rep observed, the most appropriate response is:', 'intermediate'),
  (4, 59, 'A customer says ''another contractor said the warranty covers everything.'' The most honest response is:', 'intermediate'),
  (4, 60, 'When discussing ponding water with a customer, the industry standard threshold for acceptable ponding is:', 'intermediate'),
  (4, 61, 'A customer says ''rejuvenation is a scam.'' The most appropriate response includes:', 'intermediate'),
  (4, 62, 'A customer with persistent ceiling-tile staining inside a commercial building asks for a roof patch quote. Roof inspection shows no visible failure. The most appropriate response is:', 'advanced'),
  (4, 63, 'A homeowner has installed a ridge vent and gable vents on the same roof. The likely effect is:', 'advanced'),
  (4, 64, 'A homeowner asks the rep to skip the ventilation upgrade on a re-roof to save cost. The most honest response is:', 'advanced'),
  (4, 65, 'A customer says ''you''re being too thorough — just give me a number.'' The most honest response is:', 'advanced'),
  (5, 66, 'Composition shingles are surfaced with what protective material?', 'beginner'),
  (5, 67, 'On a concrete tile roof, the actual waterproofing layer is:', 'beginner'),
  (5, 68, 'Concrete tiles themselves typically last:', 'beginner'),
  (5, 69, 'TPO seams are joined by:', 'beginner'),
  (5, 70, 'The protective layer applied over cured SPF foam is called:', 'beginner'),
  (5, 71, 'USA Flat Roof installs which type of modified bitumen?', 'beginner'),
  (5, 72, 'Roof rejuvenation is appropriate for:', 'beginner'),
  (5, 73, 'A standard silicone coating warranty typically covers:', 'intermediate'),
  (5, 74, 'The primary technical reason a restaurant or commercial kitchen might specify PVC over TPO is:', 'intermediate'),
  (5, 75, 'The primary long-term aging mechanism in PVC is:', 'intermediate'),
  (5, 76, 'A 60-mil mechanically attached TPO roof in NorCal commonly performs in the field for:', 'intermediate'),
  (5, 77, 'Pipe boots most commonly fail because:', 'intermediate'),
  (5, 78, 'The primary practical advantage of self-adhered modified bitumen installation over torch-down is:', 'intermediate'),
  (5, 79, 'USA Flat Roof installs SPF for which three primary use cases?', 'advanced'),
  (5, 80, 'A homeowner asks ''How many years will rejuvenation add to my roof?'' The most accurate response is:', 'advanced'),
  (6, 81, 'Which of the following systems can correct ponding water through tapered application during installation?', 'beginner'),
  (6, 82, 'Which roof system has the longest documented field track record in commercial use?', 'beginner'),
  (6, 83, 'Compared to silicone coatings, acrylic coatings typically:', 'intermediate'),
  (6, 84, 'Compared to TPO, PVC is generally:', 'intermediate'),
  (6, 85, 'A composition shingle roof in mid-life with sound substrate is most appropriately addressed with:', 'intermediate'),
  (6, 86, 'Compared to single-ply systems, modified bitumen offers:', 'intermediate'),
  (6, 87, 'When comparing two coating proposals — one substantially cheaper than the other on the same product — the meaningful evaluation is usually:', 'intermediate'),
  (6, 88, 'A property manager asks USA Flat Roof to quote like-for-like BUR replacement. The most appropriate response is:', 'advanced'),
  (6, 89, 'A homeowner has both a pitched composition shingle main roof and a flat-roof section over the back addition. The flat section will likely require:', 'advanced'),
  (6, 90, 'Across systems, the four most common locations for roof leaks are:', 'advanced'),
  (7, 91, 'A customer says ''you''re more expensive than the other guys.'' The most appropriate first response is:', 'beginner'),
  (7, 92, 'A customer says ''just patch where it''s leaking.'' On a 24-year-old roof with multiple leak repairs in the last 18 months. The most appropriate response is:', 'beginner'),
  (7, 93, 'A property manager dismisses ponding concerns because ''another contractor said it''s fine.'' The most appropriate response is:', 'intermediate'),
  (7, 94, 'A customer pushes back hard on the rep''s honest recommendation and demands a cheaper alternative the rep believes won''t perform. The most appropriate response is:', 'intermediate'),
  (7, 95, 'A storm-damage customer says ''insurance will cover this.'' The most appropriate response is:', 'intermediate'),
  (7, 96, 'A customer asks the rep to add scope to ''maximize the insurance claim.'' The most honest response is:', 'intermediate'),
  (7, 97, 'A customer dismisses detail-focused inspection as ''looking for problems.'' The most honest response is:', 'intermediate'),
  (7, 98, 'When a customer chooses another contractor after the rep gave the honest answer, the most appropriate rep response is:', 'advanced'),
  (7, 99, 'A long-term maintenance customer''s roof has reached end of life. The most appropriate response is:', 'advanced'),
  (7, 100, 'Across all customer outcomes — closed deal, deferred deal, lost deal, referral — the rep''s behavioral pattern should be:', 'advanced')
) AS v(section_number, question_number, question_text, difficulty)
JOIN quizzes q ON q.is_final_exam = TRUE
JOIN quiz_sections qs ON qs.quiz_id = q.id AND qs.section_number = v.section_number
ON CONFLICT ON CONSTRAINT quiz_questions_quiz_id_question_number_key DO UPDATE SET
  quiz_section_id = EXCLUDED.quiz_section_id,
  question_text = EXCLUDED.question_text,
  difficulty = EXCLUDED.difficulty,
  display_order = EXCLUDED.display_order;
DELETE FROM quiz_answers WHERE question_id IN (
  SELECT qq.id FROM quiz_questions qq JOIN quizzes q ON qq.quiz_id = q.id WHERE q.is_final_exam = TRUE
);
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (1, 'A', 'TPO', FALSE, 'TPO has factory-uniform smooth finish, not orange-peel texture.', 1),
  (1, 'B', 'PVC', FALSE, 'PVC has factory-uniform smooth finish similar to TPO.', 2),
  (1, 'C', 'Silicone coating only', FALSE, 'Silicone-only coatings have brush/spray texture but not the characteristic orange-peel of foam.', 3),
  (1, 'D', 'SPF', TRUE, 'Orange-peel texture is the SPF distinguisher. Reference: Chapter 10, Chapter 17.', 4),
  (2, 'A', 'TPO', FALSE, 'TPO is almost always white with welded seams.', 1),
  (2, 'B', 'PVC', FALSE, 'PVC is almost always white with welded seams.', 2),
  (2, 'C', 'EPDM', TRUE, 'Black color and non-welded seams are EPDM signatures. Reference: Chapter 17.', 3),
  (2, 'D', 'Modified bitumen', FALSE, 'Modified bitumen has asphalt-bonded seams, not glued or taped.', 4),
  (3, 'A', 'Color of the shingles', FALSE, 'Color varies widely and is not reliable.', 1),
  (3, 'B', 'Granular surface texture', TRUE, 'None of the look-alikes have this; it''s the composition shingle hallmark. Reference: Chapter 18.', 2),
  (3, 'C', 'Pitch of the roof', FALSE, 'Pitch varies on composition shingle homes.', 3),
  (3, 'D', 'Age of the home', FALSE, 'Age suggests but doesn''t confirm system.', 4),
  (4, 'A', 'TPO', FALSE, 'TPO is single-ply, no gravel.', 1),
  (4, 'B', 'PVC', FALSE, 'PVC is single-ply, no gravel.', 2),
  (4, 'C', 'EPDM', FALSE, 'EPDM is single-ply, no gravel.', 3),
  (4, 'D', 'BUR', TRUE, 'Gravel surface with multi-ply construction is the defining BUR feature. Reference: Chapter 9.', 4),
  (5, 'A', 'Total polymer overlay', FALSE, 'Not a real term.', 1),
  (5, 'B', 'Thermoplastic polyolefin', TRUE, 'Standard chemistry name. Reference: Chapter 2.', 2),
  (5, 'C', 'Treated polyester oxide', FALSE, 'Not a real term.', 3),
  (5, 'D', 'Thermo-protected oxide', FALSE, 'Not a real term.', 4),
  (6, 'A', 'Plasticized vinyl coating', FALSE, 'Not the chemistry name.', 1),
  (6, 'B', 'Polyvinyl chloride', TRUE, 'Standard chemistry name. Reference: Chapter 5.', 2),
  (6, 'C', 'Polymer vapor compound', FALSE, 'Not a real term.', 3),
  (6, 'D', 'Polyethylene vinyl coating', FALSE, 'Not the chemistry name.', 4),
  (7, 'A', 'The width of a TPO roll', FALSE, 'Roll width is measured in feet.', 1),
  (7, 'B', 'The thickness of the membrane', TRUE, 'A mil is one-thousandth of an inch. Reference: Chapter 2.', 2),
  (7, 'C', 'The fastener spacing', FALSE, 'Fastener spacing is measured in inches.', 3),
  (7, 'D', 'The warranty length', FALSE, 'Warranty is measured in years.', 4),
  (8, 'A', 'Three-tab shingle', FALSE, 'Three-tab is single-layer with cutout pattern.', 1),
  (8, 'B', 'Architectural (dimensional, laminated) shingle', TRUE, 'Standard description. Reference: Chapter 1.', 2),
  (8, 'C', 'Designer shingle', FALSE, 'Designer is heavier, multi-layer mimicking premium materials.', 3),
  (8, 'D', 'Wood shake', FALSE, 'Wood shake has visible grain, not shadowed dimensional appearance.', 4),
  (9, 'A', 'Color (TPO is white, PVC is gray)', FALSE, 'Both are typically white.', 1),
  (9, 'B', 'Subtle differences in surface feel and weld bead — neither can be reliably certified by appearance alone', TRUE, 'Visual confirmation is unreliable; documentation is the answer. Reference: Chapters 2, 5, 17.', 2),
  (9, 'C', 'Seam type (TPO is welded, PVC is glued)', FALSE, 'Both are welded.', 3),
  (9, 'D', 'Thickness', FALSE, 'Both come in similar thickness ranges.', 4),
  (10, 'A', 'Profile shape only', FALSE, 'Profile is shared between both.', 1),
  (10, 'B', 'Tap sound — concrete has a dull thud; clay has a higher-pitched ring', TRUE, 'Tap test is the most reliable distinguisher. Reference: Chapter 8, Chapter 18.', 2),
  (10, 'C', 'Color always', FALSE, 'Color is unreliable since concrete can be coated to mimic clay.', 3),
  (10, 'D', 'There is no reliable difference', FALSE, 'Reliable differences exist.', 4),
  (11, 'A', 'Identifying the warranty terms', FALSE, 'Warranty doesn''t establish system identification.', 1),
  (11, 'B', 'Looking at surface color (white/light, dark, or gravel)', TRUE, 'First step of the four-step decision tree. Reference: Chapter 17.', 2),
  (11, 'C', 'Checking the building age', FALSE, 'Building age is part of the building-use lens, used before climbing the ladder.', 3),
  (11, 'D', 'Asking the customer', FALSE, 'Customer report is one input, not the first step in physical identification.', 4),
  (12, 'A', 'None — building age doesn''t affect inspection', FALSE, 'Pre-1980s creates real considerations.', 1),
  (12, 'B', 'Asbestos potential, layer count assessment, and substrate identification', TRUE, 'All three are critical for pre-1980s buildings. Reference: Chapter 9.', 2),
  (12, 'C', 'Confirming the warranty is current', FALSE, 'Warranty isn''t the building-age inspection priority.', 3),
  (12, 'D', 'Requiring drone inspection only', FALSE, 'Method choice depends on safety and access, not age alone.', 4),
  (13, 'A', 'TPO', FALSE, 'TPO has less grease resistance than PVC.', 1),
  (13, 'B', 'PVC', TRUE, 'Restaurant + grease + held up well = PVC''s chemical/grease resistance is the technical reason. Reference: Chapter 5.', 2),
  (13, 'C', 'EPDM', FALSE, 'EPDM is typically black with non-welded seams.', 3),
  (13, 'D', 'Modified bitumen', FALSE, 'Mod-bit doesn''t have welded seams.', 4),
  (14, 'A', 'Confirming coating chemistry only', FALSE, 'Chemistry matters but substrate matters more.', 1),
  (14, 'B', 'Identifying the substrate underneath the coating', TRUE, 'Substrate determines future scope options. Reference: Chapter 17.', 2),
  (14, 'C', 'Checking the manufacturer logo', FALSE, 'Logos are rarely visible on coatings.', 3),
  (14, 'D', 'Measuring slope only', FALSE, 'Slope matters but substrate identification is the priority.', 4),
  (15, 'A', 'Real clay tile', FALSE, 'Less common on tract homes; concrete with clay-mimic coating is more common.', 1),
  (15, 'B', 'Concrete tile (pigmented or surface-coated to mimic clay)', TRUE, 'Matches the era and tract-home pattern in NorCal. Reference: Chapter 18.', 2),
  (15, 'C', 'Stone-coated metal', FALSE, 'Less common; would have metallic tap sound.', 3),
  (15, 'D', 'Composition shingle', FALSE, 'Composition shingle has flat profile, not barrel.', 4),
  (16, 'A', 'Real wood shake', FALSE, 'Real wood has a soft thunk, not plastic pop.', 1),
  (16, 'B', 'Synthetic / composite shake', TRUE, 'Plastic-pop tap is the give-away. Reference: Chapter 18.', 2),
  (16, 'C', 'Composition shake-look shingle', FALSE, 'Composition wouldn''t be described as ''wood shake'' by a homeowner.', 3),
  (16, 'D', 'Stone-coated metal', FALSE, 'Metal would have metallic sound.', 4),
  (17, 'A', 'TPO with original installation', FALSE, 'TPO has welded seams visible.', 1),
  (17, 'B', 'New EPDM', FALSE, 'EPDM has glued/taped seams.', 2),
  (17, 'C', 'A coated roof — silicone or acrylic over an existing substrate', TRUE, 'Continuous painted-looking surface with brush texture and no welded seams indicates coating. Reference: Chapter 17.', 3),
  (17, 'D', 'SPF only', FALSE, 'SPF has orange-peel texture distinct from brush texture.', 4),
  (18, 'A', 'Confirm TPO based on the white color', FALSE, 'Color is shared between TPO and PVC.', 1),
  (18, 'B', 'Confirm PVC because the surface feels slick', FALSE, 'Surface feel is unreliable for certification.', 2),
  (18, 'C', 'Document the visual indicators and note that product type cannot be certified without documentation', TRUE, 'Visual confirmation is unreliable. Reference: Chapter 17.', 3),
  (18, 'D', 'Defer to the customer''s belief', FALSE, 'Customer belief without verification isn''t certification.', 4),
  (19, 'A', 'The same inspection approach as the composition shingle', FALSE, 'Different system requires different approach.', 1),
  (19, 'B', 'The commercial-system identification approach (Chapter 17)', TRUE, 'Flat sections require commercial-system identification.', 2),
  (19, 'C', 'No inspection — flat sections don''t matter on residential', FALSE, 'Flat sections are part of the home.', 3),
  (19, 'D', 'Drone-only inspection', FALSE, 'Method depends on access and safety.', 4),
  (20, 'A', 'Confirm the homeowner is correct', FALSE, 'Observation suggests synthetic, not real slate.', 1),
  (20, 'B', 'Document what was observed (synthetic / composite slate appearance), explain the indicators that suggest it''s not real slate, and ask if they have product documentation', TRUE, 'Honest framework. Reference: Chapter 18.', 2),
  (20, 'C', 'Tell the homeowner they''re wrong', FALSE, 'Unprofessional; explain the observations.', 3),
  (20, 'D', 'Quote work as real slate based on the homeowner''s report', FALSE, 'Quoting on unverified information creates problems.', 4)
) AS v(question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN quizzes q ON q.is_final_exam = TRUE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
COMMIT;
