BEGIN;
-- Chunk D: chapter quizzes (compact SELECT-FROM-VALUES form) (part 1/4)
INSERT INTO quizzes (chapter_id, title, passing_score_percent, question_count, is_final_exam, retake_cooldown_hours, allow_section_review)
SELECT c.id, v.title, 70, 10, FALSE, 24, TRUE
FROM (VALUES
  (1, 1, 'Chapter 1 Quiz - Composition Shingle'),
  (1, 2, 'Chapter 2 Quiz - TPO (Thermoplastic Polyolefin)'),
  (1, 3, 'Chapter 3 Quiz - Silicone Coatings'),
  (1, 4, 'Chapter 4 Quiz - Roof Rejuvenation (Fresh Roof)'),
  (1, 5, 'Chapter 5 Quiz - PVC (Polyvinyl Chloride)'),
  (1, 6, 'Chapter 6 Quiz - Modified Bitumen (Self-Adhered)'),
  (1, 7, 'Chapter 7 Quiz - Acrylic Coatings'),
  (1, 8, 'Chapter 8 Quiz - Concrete Tile'),
  (1, 9, 'Chapter 9 Quiz - Built-Up Roofing (BUR)'),
  (1, 10, 'Chapter 10 Quiz - Spray Polyurethane Foam (SPF)'),
  (2, 11, 'Chapter 11 Quiz - Maintenance and Repairs'),
  (2, 12, 'Chapter 12 Quiz - Inspections and Documentation'),
  (2, 13, 'Chapter 13 Quiz - Repair vs Restoration vs Replacement Decision Framework'),
  (2, 14, 'Chapter 14 Quiz - Ventilation and Condensation'),
  (2, 15, 'Chapter 15 Quiz - Flashings, Penetrations, and Edge Details'),
  (2, 16, 'Chapter 16 Quiz - Gutters, Drainage, and Ponding Water'),
  (2, 17, 'Chapter 17 Quiz - Commercial Flat-Roof Systems Overview'),
  (2, 18, 'Chapter 18 Quiz - Residential Steep-Slope Roof Systems Overview')
) AS v(part_num, chap_num, title)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
ON CONFLICT (chapter_id) DO UPDATE SET
  title = EXCLUDED.title,
  passing_score_percent = EXCLUDED.passing_score_percent,
  question_count = EXCLUDED.question_count,
  is_final_exam = EXCLUDED.is_final_exam,
  retake_cooldown_hours = EXCLUDED.retake_cooldown_hours,
  allow_section_review = EXCLUDED.allow_section_review;
INSERT INTO quiz_questions (quiz_id, quiz_section_id, question_number, question_text, difficulty, display_order)
SELECT q.id, NULL, v.question_number, v.question_text, v.difficulty, v.question_number
FROM (VALUES
  (1, 1, 1, 'The granular surface on a composition shingle is composed of:', 'beginner'),
  (1, 1, 2, 'The most common composition shingle profile installed today is:', 'beginner'),
  (1, 1, 3, 'Expected NorCal field lifespan for architectural composition shingles is:', 'beginner'),
  (1, 1, 4, 'Granules in the gutters are most commonly a sign of:', 'intermediate'),
  (1, 1, 5, 'Inadequate attic ventilation accelerates shingle aging primarily by:', 'intermediate'),
  (1, 1, 6, '''Lifetime warranty'' on shingles typically means:', 'intermediate'),
  (1, 1, 7, 'A 12-year-old architectural shingle roof with a single failed pipe boot, otherwise good, is best addressed with:', 'intermediate'),
  (1, 1, 8, 'Algae streaking on the north slope is best treated with:', 'intermediate'),
  (1, 1, 9, 'A 23-year-old three-tab roof with widespread granule loss exposing asphalt, multiple lifted shingles, and active leaks is best addressed with:', 'advanced'),
  (1, 1, 10, 'When a customer asks ''how long will my new shingle roof last?'', the honest response is:', 'advanced'),
  (1, 2, 1, 'TPO seams are joined using:', 'beginner'),
  (1, 2, 2, 'USA Flat Roof''s standard TPO specification is:', 'beginner'),
  (1, 2, 3, 'The most common color of TPO membrane in NorCal commercial is:', 'beginner'),
  (1, 2, 4, 'Where do most TPO leaks originate?', 'intermediate'),
  (1, 2, 5, 'T-joints (where three TPO sheets meet) are noteworthy because:', 'intermediate'),
  (1, 2, 6, 'Fastener bumps under the membrane along seams typically indicate:', 'intermediate'),
  (1, 2, 7, 'A 16-year-old TPO with sound seams, no chronic ponding, addressable details is best addressed with:', 'intermediate'),
  (1, 2, 8, 'TPO membrane under HVAC equipment can fail because of:', 'intermediate'),
  (1, 2, 9, 'A property manager wants TPO replacement on a chronically ponded roof. The honest response is:', 'advanced'),
  (1, 2, 10, 'Comparing three TPO proposals at very different prices, the rep should:', 'advanced'),
  (1, 3, 1, 'Silicone coating is best understood as:', 'beginner'),
  (1, 3, 2, 'Silicone coatings excel at:', 'beginner'),
  (1, 3, 3, 'A silicone coating warranty typically covers:', 'beginner'),
  (1, 3, 4, 'Disqualifying conditions for silicone restoration include:', 'intermediate'),
  (1, 3, 5, 'Fabric reinforcement in silicone is typically applied at:', 'intermediate'),
  (1, 3, 6, 'When applying silicone over an existing acrylic-coated roof, the rep should:', 'intermediate'),
  (1, 3, 7, 'A property owner with a chronically ponded roof asks for silicone restoration. The honest response is:', 'intermediate'),
  (1, 3, 8, 'Service life extension from silicone restoration on qualifying substrate is typically:', 'intermediate'),
  (1, 3, 9, 'When a coating fails in ponded areas before warranty period, this typically indicates:', 'advanced'),
  (1, 3, 10, 'A repeat customer pushes for silicone on a non-qualifying substrate. The most appropriate response is:', 'advanced'),
  (1, 4, 1, 'Roof rejuvenation is appropriate for which roof type?', 'beginner'),
  (1, 4, 2, 'Rejuvenation works at the chemical level by:', 'beginner'),
  (1, 4, 3, 'USA Flat Roof positions Fresh Roof rejuvenation as:', 'beginner'),
  (1, 4, 4, 'After rejuvenation, the visible appearance of the roof typically:', 'intermediate'),
  (1, 4, 5, 'A roof outside the qualifying age window for rejuvenation should be:', 'intermediate'),
  (1, 4, 6, 'When asked ''how many years will rejuvenation add?'', the most accurate answer is:', 'intermediate'),
  (1, 4, 7, 'Disqualifying conditions for rejuvenation include:', 'intermediate'),
  (1, 4, 8, 'When a customer says ''is rejuvenation a scam?'', the most appropriate response includes:', 'intermediate'),
  (1, 4, 9, 'A homeowner says rejuvenation will save them from replacement entirely. The accurate response is:', 'advanced'),
  (1, 4, 10, 'Fresh Roof rejuvenation works best when integrated into:', 'advanced'),
  (1, 5, 1, 'PVC and TPO seams are joined by the same method:', 'beginner'),
  (1, 5, 2, 'PVC is positioned by USA Flat Roof as:', 'beginner'),
  (1, 5, 3, 'The primary aging mechanism in PVC is:', 'beginner'),
  (1, 5, 4, 'A restaurant with significant kitchen exhaust most likely has PVC because:', 'intermediate'),
  (1, 5, 5, 'When a rep cannot certify TPO vs PVC by appearance, the appropriate documentation is:', 'intermediate'),
  (1, 5, 6, 'Plasticizer migration is most visible on PVC roofs that are approximately:', 'intermediate'),
  (1, 5, 7, 'Standard PVC field lifespan in NorCal is approximately:', 'intermediate'),
  (1, 5, 8, 'A 28-year-old PVC roof with widespread membrane stiffening, multiple cracked areas, and chronic ponding should be addressed with:', 'intermediate'),
  (1, 5, 9, 'When silicone restoration is being applied over existing PVC, the critical step is:', 'advanced'),
  (1, 5, 10, 'A property manager compares a PVC and TPO proposal at significantly different prices. The rep should:', 'advanced'),
  (1, 6, 1, 'USA Flat Roof installs which modified bitumen installation method?', 'beginner'),
  (1, 6, 2, 'Modified bitumen is best understood as:', 'beginner'),
  (1, 6, 3, 'Self-adhered modified bitumen seams typically appear:', 'beginner'),
  (1, 6, 4, 'The primary practical advantage of self-adhered over torch-down is:', 'intermediate'),
  (1, 6, 5, 'When customer asks USA Flat Roof to torch-down a replacement, the rep should:', 'intermediate'),
  (1, 6, 6, 'Modified bitumen blistering most commonly indicates:', 'intermediate'),
  (1, 6, 7, 'Existing torch-down or hot-mopped roofs encountered on inspection:', 'intermediate'),
  (1, 6, 8, 'Modified bitumen field lifespan in NorCal is approximately:', 'intermediate'),
  (1, 6, 9, 'Mid-life modified bitumen with sound substrate is best addressed with:', 'intermediate'),
  (1, 6, 10, 'When customer wants to compare self-adhered and torch-down replacement quote, the rep should:', 'advanced')
) AS v(part_num, chap_num, question_number, question_text, difficulty)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
JOIN quizzes q ON q.chapter_id = c.id AND q.is_final_exam = FALSE
ON CONFLICT ON CONSTRAINT quiz_questions_quiz_id_question_number_key DO UPDATE SET
  question_text = EXCLUDED.question_text,
  difficulty = EXCLUDED.difficulty,
  display_order = EXCLUDED.display_order;
INSERT INTO quiz_questions (quiz_id, quiz_section_id, question_number, question_text, difficulty, display_order)
SELECT q.id, NULL, v.question_number, v.question_text, v.difficulty, v.question_number
FROM (VALUES
  (1, 7, 1, 'Acrylic coatings are positioned by USA Flat Roof as:', 'beginner'),
  (1, 7, 2, 'Compared to silicone, acrylic coatings typically:', 'intermediate'),
  (1, 7, 3, 'When a rep encounters existing acrylic-coated roof and customer wants silicone restoration, the rep should:', 'intermediate'),
  (1, 7, 4, 'Visual distinction between silicone and acrylic coatings is:', 'intermediate'),
  (1, 7, 5, 'Acrylic coating service life is approximately:', 'intermediate'),
  (1, 7, 6, 'USA Flat Roof''s primary recommendation for new restoration coating is:', 'intermediate'),
  (1, 7, 7, 'An acrylic coating on a roof with chronic ponding is likely to:', 'intermediate'),
  (1, 7, 8, 'Recoat compatibility from acrylic to silicone is:', 'advanced'),
  (1, 7, 9, 'USA Flat Roof''s response to a customer who specifically requests acrylic restoration is:', 'advanced'),
  (1, 7, 10, 'Aluminum-pigmented asphalt coating on aged BUR or modified bitumen is best understood as:', 'advanced'),
  (1, 8, 1, 'On a concrete tile roof, the actual waterproofing layer is:', 'beginner'),
  (1, 8, 2, 'Concrete tiles typically last:', 'beginner'),
  (1, 8, 3, 'Underlayment beneath concrete tiles typically lasts:', 'beginner'),
  (1, 8, 4, 'USA Flat Roof''s scope on concrete tile work is:', 'intermediate'),
  (1, 8, 5, 'Concrete vs clay tile is most reliably distinguished by:', 'intermediate'),
  (1, 8, 6, 'Walking on tile roofs requires:', 'intermediate'),
  (1, 8, 7, 'Active interior leaks under a 25-year-old concrete tile roof most commonly indicate:', 'intermediate'),
  (1, 8, 8, 'Mortar deterioration at the ridge is best addressed with:', 'intermediate'),
  (1, 8, 9, 'A customer with a 28-year-old tile roof has multiple recent leaks. The most likely diagnosis is:', 'advanced'),
  (1, 8, 10, 'Broken or cracked individual tiles encountered during inspection are typically addressed by:', 'advanced'),
  (1, 9, 1, 'USA Flat Roof''s position on installing new BUR is:', 'beginner'),
  (1, 9, 2, 'BUR is best identified by:', 'beginner'),
  (1, 9, 3, 'BUR field lifespan is typically:', 'beginner'),
  (1, 9, 4, 'USA Flat Roof''s recommendation framework on a single-layer BUR is:', 'intermediate'),
  (1, 9, 5, 'Layer count on BUR substrates is critical because:', 'intermediate'),
  (1, 9, 6, 'Pre-1980s BUR buildings require what additional inspection priority?', 'intermediate'),
  (1, 9, 7, 'BUR pitch pans are most commonly addressed because:', 'intermediate'),
  (1, 9, 8, 'An aged BUR with light surface wear, intact gravel coverage, sound substrate, no asbestos suspected is best addressed with:', 'intermediate'),
  (1, 9, 9, 'SPF as an option on BUR substrates is appropriate when:', 'advanced'),
  (1, 9, 10, 'When a property owner asks USA Flat Roof to install new BUR, the appropriate response is:', 'advanced'),
  (1, 10, 1, 'The most reliable visual identifier of SPF is:', 'beginner'),
  (1, 10, 2, 'The protective layer applied over cured SPF foam is called:', 'beginner'),
  (1, 10, 3, 'USA Flat Roof installs SPF for which three primary use cases?', 'beginner'),
  (1, 10, 4, 'SPF foam itself can last:', 'intermediate'),
  (1, 10, 5, 'The topcoat recoat schedule on SPF is typically:', 'intermediate'),
  (1, 10, 6, 'SPF can correct ponding because:', 'intermediate'),
  (1, 10, 7, 'Exposed foam (without topcoat) on an SPF roof typically indicates:', 'intermediate'),
  (1, 10, 8, 'Walk pads on SPF roofs are installed to:', 'intermediate'),
  (1, 10, 9, 'An SPF customer who skips the topcoat recoat schedule:', 'advanced'),
  (1, 10, 10, 'When SPF is recommended specifically because of ponding, the rep should also discuss:', 'advanced'),
  (2, 11, 1, 'USA Flat Roof''s maintenance program is positioned as:', 'beginner'),
  (2, 11, 2, 'When a customer reports a leak, the inspection should:', 'beginner'),
  (2, 11, 3, 'The leak entry point on a roof is typically:', 'beginner'),
  (2, 11, 4, 'A 24-year-old roof with three leak repairs in 18 months suggests:', 'intermediate'),
  (2, 11, 5, 'The ''repair-plus-plan'' conversation is appropriate when:', 'intermediate'),
  (2, 11, 6, 'A maintenance call reveals an Urgent severity condition the rep is not authorized to address. The response is:', 'intermediate'),
  (2, 11, 7, 'A long-term maintenance customer''s roof has reached end of life. The honest response is:', 'intermediate'),
  (2, 11, 8, 'Service call minimums and emergency premiums:', 'intermediate'),
  (2, 11, 9, 'When a customer says ''just patch it where it''s leaking'' on a 24-year-old roof, the rep should:', 'advanced'),
  (2, 11, 10, 'Rep''s response to a customer who pushes for repair-only on a clearly end-of-life roof is:', 'advanced'),
  (2, 12, 1, 'The four-point Inspection Severity Scale is:', 'beginner'),
  (2, 12, 2, 'The three audiences for inspection documentation are:', 'beginner'),
  (2, 12, 3, 'The four pillars of inspection are:', 'beginner'),
  (2, 12, 4, 'Drone inspection is most valuable for:', 'intermediate'),
  (2, 12, 5, 'Documenting ponding evidence on a dry-day inspection requires:', 'intermediate'),
  (2, 12, 6, 'A reference scale in damage photos is:', 'intermediate'),
  (2, 12, 7, 'When a customer asks for verbal pricing during inspection, the appropriate response is:', 'intermediate'),
  (2, 12, 8, 'Reps may NOT certify which of the following?', 'intermediate'),
  (2, 12, 9, 'When a leak source cannot be identified after full inspection, the next step is:', 'advanced'),
  (2, 12, 10, 'When customer says ''documentation is too thorough — just give me a number'', rep should:', 'advanced')
) AS v(part_num, chap_num, question_number, question_text, difficulty)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
JOIN quizzes q ON q.chapter_id = c.id AND q.is_final_exam = FALSE
ON CONFLICT ON CONSTRAINT quiz_questions_quiz_id_question_number_key DO UPDATE SET
  question_text = EXCLUDED.question_text,
  difficulty = EXCLUDED.difficulty,
  display_order = EXCLUDED.display_order;
INSERT INTO quiz_questions (quiz_id, quiz_section_id, question_number, question_text, difficulty, display_order)
SELECT q.id, NULL, v.question_number, v.question_text, v.difficulty, v.question_number
FROM (VALUES
  (2, 13, 1, '''Repair'' in the four-scope framework is best described as:', 'beginner'),
  (2, 13, 2, '''Restoration'' is best described as:', 'beginner'),
  (2, 13, 3, '''Recover (overlay)'' is best described as:', 'beginner'),
  (2, 13, 4, 'The four decision lenses for recommendations, in order, are:', 'intermediate'),
  (2, 13, 5, 'Disqualifying conditions for restoration across most systems include:', 'intermediate'),
  (2, 13, 6, 'A customer with a 6-year-old roof in good condition asks for replacement. The honest response is:', 'intermediate'),
  (2, 13, 7, 'A 12-year-old TPO with single punctured area, otherwise excellent condition, is best addressed with:', 'intermediate'),
  (2, 13, 8, 'Phased work is appropriate when:', 'intermediate'),
  (2, 13, 9, 'A repeat customer asks for restoration on a roof the rep believes does not qualify. The response is:', 'advanced'),
  (2, 13, 10, 'When budget genuinely doesn''t fit what the roof needs, the three honest paths are:', 'advanced'),
  (2, 14, 1, 'Balanced attic ventilation requires:', 'beginner'),
  (2, 14, 2, 'Inadequate ventilation accelerates shingle aging primarily by:', 'beginner'),
  (2, 14, 3, 'A ''short-circuit'' pattern in attic ventilation occurs when:', 'beginner'),
  (2, 14, 4, 'Ridge vents and gable vents on the same roof typically:', 'intermediate'),
  (2, 14, 5, 'Most shingle manufacturer warranties:', 'intermediate'),
  (2, 14, 6, 'Vapor and condensation issues in attics are:', 'intermediate'),
  (2, 14, 7, 'Persistent ceiling stain inside a building with no visible roof failure suggests:', 'intermediate'),
  (2, 14, 8, 'Attic frost on the deck during cold conditions indicates:', 'intermediate'),
  (2, 14, 9, 'When a homeowner asks the rep to skip ventilation upgrade on re-roof to save cost, the response is:', 'advanced'),
  (2, 14, 10, 'Flat roof condensation issues are typically driven by:', 'advanced'),
  (2, 15, 1, 'Most roof leaks happen at:', 'beginner'),
  (2, 15, 2, 'Pipe boots most commonly fail because:', 'beginner'),
  (2, 15, 3, 'A ''kick-out'' flashing is:', 'beginner'),
  (2, 15, 4, 'Step flashing is found at:', 'intermediate'),
  (2, 15, 5, 'Counter-flashing is installed:', 'intermediate'),
  (2, 15, 6, 'Pitch pans require regular attention because:', 'intermediate'),
  (2, 15, 7, 'Drip edge installed behind the gutter (instead of correctly positioned) creates:', 'intermediate'),
  (2, 15, 8, 'Skylight perimeter flashings most commonly leak because of:', 'intermediate'),
  (2, 15, 9, 'A customer dismisses detail-focused inspection as ''looking for problems''. The honest response is:', 'advanced'),
  (2, 15, 10, 'Standard flashing scope on re-roof projects typically includes:', 'advanced'),
  (2, 16, 1, 'The industry standard threshold for acceptable ponding is:', 'beginner'),
  (2, 16, 2, 'Which is NOT a flat-roof drainage approach?', 'beginner'),
  (2, 16, 3, 'An overflow drain is:', 'beginner'),
  (2, 16, 4, 'A ''ponding ring'' is:', 'intermediate'),
  (2, 16, 5, 'A silicone restoration coating applied to a chronically ponded roof will:', 'intermediate'),
  (2, 16, 6, 'Which roof system can correct ponding through tapered application during installation?', 'intermediate'),
  (2, 16, 7, 'When a property manager reports water ''always sits in that one spot'', the appropriate first response is:', 'intermediate'),
  (2, 16, 8, 'Most likely cause of ponding on a 30-year-old roof that originally drained well:', 'intermediate'),
  (2, 16, 9, 'A customer wants the cheapest option to address chronic ponding. The honest options are:', 'advanced'),
  (2, 16, 10, 'A customer dismisses ponding because ''another contractor said it''s fine''. The response is:', 'advanced'),
  (2, 17, 1, 'The first question on every commercial inspection is:', 'beginner'),
  (2, 17, 2, 'A white commercial roof with welded seams is most likely:', 'beginner'),
  (2, 17, 3, 'A black single-ply with glued or taped seams is most likely:', 'beginner'),
  (2, 17, 4, 'A flat roof with characteristic orange-peel surface texture is:', 'beginner'),
  (2, 17, 5, 'When a rep cannot certify TPO vs PVC, the appropriate response is:', 'intermediate'),
  (2, 17, 6, 'The most reliable way to identify SPF vs silicone-coated single-ply is:', 'intermediate'),
  (2, 17, 7, 'A property manager says ''we have TPO''. Rep observes characteristics suggesting PVC. Response:', 'intermediate'),
  (2, 17, 8, 'On a heavily coated commercial roof, the most important identification step is:', 'intermediate'),
  (2, 17, 9, 'A 1968 commercial building with white-coated flat roof creates which inspection priorities?', 'advanced'),
  (2, 17, 10, 'A restaurant with significant kitchen exhaust shows white welded-seam membrane that has held up well around grease vents:', 'advanced'),
  (2, 18, 1, 'Most reliable indicator that a residential roof is composition shingle is:', 'beginner'),
  (2, 18, 2, 'Concrete vs clay tile most reliably differs in:', 'beginner'),
  (2, 18, 3, 'Architectural shingle is best described as:', 'beginner'),
  (2, 18, 4, 'USA Flat Roof''s residential scope includes:', 'beginner'),
  (2, 18, 5, 'A 1995 NorCal tract home with red barrel-profile roof is most likely:', 'intermediate'),
  (2, 18, 6, 'Pieces that look like wood but tap with plastic pop are:', 'intermediate'),
  (2, 18, 7, 'A 1925 Berkeley craftsman with thin gray tiles, natural stone variation, ringing tap is:', 'intermediate'),
  (2, 18, 8, 'Customer reports their roof as ''tile'' without specifying. The most appropriate next step is:', 'intermediate'),
  (2, 18, 9, 'Home with pitched composition shingle main roof and flat-roof addition. Flat section needs:', 'advanced'),
  (2, 18, 10, 'Customer says ''real slate''. Inspection shows uniform manufactured color, light weight, plastic-pop tap. Response:', 'advanced')
) AS v(part_num, chap_num, question_number, question_text, difficulty)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
JOIN quizzes q ON q.chapter_id = c.id AND q.is_final_exam = FALSE
ON CONFLICT ON CONSTRAINT quiz_questions_quiz_id_question_number_key DO UPDATE SET
  question_text = EXCLUDED.question_text,
  difficulty = EXCLUDED.difficulty,
  display_order = EXCLUDED.display_order;
DELETE FROM quiz_answers WHERE question_id IN (
  SELECT qq.id FROM quiz_questions qq JOIN quizzes q ON qq.quiz_id = q.id WHERE q.is_final_exam = FALSE
);
COMMIT;
