BEGIN;
-- Chunk D: chapter quizzes (compact SELECT-FROM-VALUES form) (part 4/4)
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (2, 13, 6, 'A', 'Write the replacement proposal', FALSE, NULL, 1),
  (2, 13, 6, 'B', 'Explain remaining life; recommend repair or maintenance instead', TRUE, 'Honest answer when customer wants more than roof needs.', 2),
  (2, 13, 6, 'C', 'Recommend silicone restoration as compromise', FALSE, NULL, 3),
  (2, 13, 6, 'D', 'Refer customer elsewhere', FALSE, NULL, 4),
  (2, 13, 7, 'A', 'Full replacement', FALSE, NULL, 1),
  (2, 13, 7, 'B', 'Silicone restoration coating', FALSE, NULL, 2),
  (2, 13, 7, 'C', 'Targeted repair of puncture, with annual maintenance recommended', TRUE, 'Young roof with localized failure.', 3),
  (2, 13, 7, 'D', 'Decline to inspect', FALSE, NULL, 4),
  (2, 13, 8, 'A', 'Customer has unlimited budget', FALSE, NULL, 1),
  (2, 13, 8, 'B', 'Customer''s budget genuinely doesn''t support full scope but the roof needs work', TRUE, 'Honest alternative when budget is constraint.', 2),
  (2, 13, 8, 'C', 'Always', FALSE, NULL, 3),
  (2, 13, 8, 'D', 'Never', FALSE, NULL, 4),
  (2, 13, 9, 'A', 'Provide because they''re a repeat customer', FALSE, NULL, 1),
  (2, 13, 9, 'B', 'Decline to propose restoration, explain why, recommend honest alternative', TRUE, 'Honest-versus-easy moment.', 2),
  (2, 13, 9, 'C', 'Provide with higher-tier product', FALSE, NULL, 3),
  (2, 13, 9, 'D', 'Refer elsewhere without explanation', FALSE, NULL, 4),
  (2, 13, 10, 'A', 'Capitulate, refer, decline', FALSE, NULL, 1),
  (2, 13, 10, 'B', 'Phased work, honest decline, or referral', TRUE, 'Three honest paths.', 2),
  (2, 13, 10, 'C', 'Discount, discount, discount', FALSE, NULL, 3),
  (2, 13, 10, 'D', 'Cut scope, cut scope, cut scope', FALSE, NULL, 4),
  (2, 14, 1, 'A', 'Exhaust vents only', FALSE, NULL, 1),
  (2, 14, 1, 'B', 'Appropriate proportions of intake and exhaust, allowing air movement through the full attic', TRUE, 'Standard ventilation principle.', 2),
  (2, 14, 1, 'C', 'Intake only', FALSE, NULL, 3),
  (2, 14, 1, 'D', 'No vents at all', FALSE, NULL, 4),
  (2, 14, 2, 'A', 'Causing wind damage', FALSE, NULL, 1),
  (2, 14, 2, 'B', 'Trapping heat that ages shingles from below', TRUE, 'Primary ventilation-driven aging mechanism.', 2),
  (2, 14, 2, 'C', 'Increasing UV exposure', FALSE, NULL, 3),
  (2, 14, 2, 'D', 'Causing snow damage', FALSE, NULL, 4),
  (2, 14, 3, 'A', 'Lightning hits the roof', FALSE, NULL, 1),
  (2, 14, 3, 'B', 'Two exhaust types pull from each other instead of pulling air through the full attic', TRUE, 'Common ventilation configuration error.', 2),
  (2, 14, 3, 'C', 'All vents fail simultaneously', FALSE, NULL, 3),
  (2, 14, 3, 'D', 'Snow blocks the soffits', FALSE, NULL, 4),
  (2, 14, 4, 'A', 'Improve ventilation through redundancy', FALSE, NULL, 1),
  (2, 14, 4, 'B', 'Create a short-circuit pattern, reducing effective ventilation', TRUE, 'Common configuration error.', 2),
  (2, 14, 4, 'C', 'Have no effect', FALSE, NULL, 3),
  (2, 14, 4, 'D', 'Affect winter only', FALSE, NULL, 4),
  (2, 14, 5, 'A', 'Don''t address ventilation', FALSE, NULL, 1),
  (2, 14, 5, 'B', 'Require adequate attic ventilation; ventilation-driven aging is a common warranty denial', TRUE, 'Standard ventilation-warranty interaction.', 2),
  (2, 14, 5, 'C', 'Cover all ventilation issues', FALSE, NULL, 3),
  (2, 14, 5, 'D', 'Penalize ventilation upgrades', FALSE, NULL, 4),
  (2, 14, 6, 'A', 'Always the rep''s scope', FALSE, NULL, 1),
  (2, 14, 6, 'B', 'Building science issues that may exceed rep authorization and require qualified assessment', TRUE, 'Vapor/moisture concerns require escalation.', 2),
  (2, 14, 6, 'C', 'Always cosmetic', FALSE, NULL, 3),
  (2, 14, 6, 'D', 'Never relevant', FALSE, NULL, 4),
  (2, 14, 7, 'A', 'A roof leak only', FALSE, NULL, 1),
  (2, 14, 7, 'B', 'Possible vapor, condensation, or assembly moisture issue requiring qualified assessment', TRUE, 'Vapor concern indicators.', 2),
  (2, 14, 7, 'C', 'HOA violation', FALSE, NULL, 3),
  (2, 14, 7, 'D', 'Cosmetic damage only', FALSE, NULL, 4),
  (2, 14, 8, 'A', 'Normal seasonal pattern', FALSE, NULL, 1),
  (2, 14, 8, 'B', 'Inadequate ventilation allowing moisture to condense', TRUE, 'Ventilation indicator.', 2),
  (2, 14, 8, 'C', 'Manufacturing defect', FALSE, NULL, 3),
  (2, 14, 8, 'D', 'Customer abuse', FALSE, NULL, 4),
  (2, 14, 9, 'A', 'Skip without comment', FALSE, NULL, 1),
  (2, 14, 9, 'B', 'Explain ventilation drives roof life and warranty coverage; document if customer still declines', TRUE, 'Honest framework.', 2),
  (2, 14, 9, 'C', 'Insist customer accept upgrade', FALSE, NULL, 3),
  (2, 14, 9, 'D', 'Refer elsewhere', FALSE, NULL, 4),
  (2, 14, 10, 'A', 'Poor membrane choice', FALSE, NULL, 1),
  (2, 14, 10, 'B', 'Vapor moving from interior into the assembly, not roof leaks; requires assembly-level diagnosis', TRUE, 'Flat roof vapor patterns.', 2),
  (2, 14, 10, 'C', 'External temperature alone', FALSE, NULL, 3),
  (2, 14, 10, 'D', 'Rain', FALSE, NULL, 4),
  (2, 15, 1, 'A', 'Center of the field', FALSE, NULL, 1),
  (2, 15, 1, 'B', 'Penetrations, transitions, edges, and valleys/drains', TRUE, 'Universal leak pattern.', 2),
  (2, 15, 1, 'C', 'Random locations', FALSE, NULL, 3),
  (2, 15, 1, 'D', 'The deck', FALSE, NULL, 4),
  (2, 15, 2, 'A', 'Manufacturer defects', FALSE, NULL, 1),
  (2, 15, 2, 'B', 'UV degradation cracking the rubber, particularly at the top where the boot wraps the pipe', TRUE, 'Most common failure mechanism.', 2),
  (2, 15, 2, 'C', 'Wind damage', FALSE, NULL, 3),
  (2, 15, 2, 'D', 'Snow load', FALSE, NULL, 4),
  (2, 15, 3, 'A', 'A type of valley flashing', FALSE, NULL, 1),
  (2, 15, 3, 'B', 'A small piece at the bottom of step flashing that diverts water away from the wall and into the gutter', TRUE, 'Standard kick-out function.', 2),
  (2, 15, 3, 'C', 'A vent type', FALSE, NULL, 3),
  (2, 15, 3, 'D', 'An edge metal', FALSE, NULL, 4),
  (2, 15, 4, 'A', 'Ridges only', FALSE, NULL, 1),
  (2, 15, 4, 'B', 'The sidewalls of sloped roofs, with each piece overlapping the one below', TRUE, 'Standard step flashing location.', 2),
  (2, 15, 4, 'C', 'The center of the field', FALSE, NULL, 3),
  (2, 15, 4, 'D', 'Skylights only', FALSE, NULL, 4),
  (2, 15, 5, 'A', 'Only on commercial roofs', FALSE, NULL, 1),
  (2, 15, 5, 'B', 'Over a base flashing (such as step flashing) to direct water away and protect the joint', TRUE, 'Standard counter-flashing function.', 2),
  (2, 15, 5, 'C', 'Beneath the membrane only', FALSE, NULL, 3),
  (2, 15, 5, 'D', 'On flat surfaces only', FALSE, NULL, 4),
  (2, 15, 6, 'A', 'They never fail', FALSE, NULL, 1),
  (2, 15, 6, 'B', 'Their sealant degrades over time, making them a high-failure detail', TRUE, 'Pitch pan recurring maintenance.', 2),
  (2, 15, 6, 'C', 'They block ventilation', FALSE, NULL, 3),
  (2, 15, 6, 'D', 'They affect drainage', FALSE, NULL, 4),
  (2, 15, 7, 'A', 'Better drainage', FALSE, NULL, 1),
  (2, 15, 7, 'B', 'Water that runs down the fascia behind the gutter, leading to fascia rot and roof edge issues', TRUE, 'Common drip edge installation error.', 2),
  (2, 15, 7, 'C', 'No effect', FALSE, NULL, 3),
  (2, 15, 7, 'D', 'Improved aesthetics', FALSE, NULL, 4),
  (2, 15, 8, 'A', 'Customer use', FALSE, NULL, 1),
  (2, 15, 8, 'B', 'Aging perimeter seal, frame seal, or improper installation', TRUE, 'Common skylight failure modes.', 2),
  (2, 15, 8, 'C', 'Manufacturer defects only', FALSE, NULL, 3),
  (2, 15, 8, 'D', 'Wind', FALSE, NULL, 4),
  (2, 15, 9, 'A', 'Apologize and reduce scope', FALSE, NULL, 1),
  (2, 15, 9, 'B', 'Explain that details are where roofs typically leak; offer the customer the choice with caveats', TRUE, 'Honest response.', 2),
  (2, 15, 9, 'C', 'Skip detail inspection', FALSE, NULL, 3),
  (2, 15, 9, 'D', 'Tell them they need no work', FALSE, NULL, 4),
  (2, 15, 10, 'A', 'Reuse all existing flashings', FALSE, NULL, 1),
  (2, 15, 10, 'B', 'Replacement of all flashings, with reuse only where conditions support it', TRUE, 'Standard practice.', 2),
  (2, 15, 10, 'C', 'Random selection', FALSE, NULL, 3),
  (2, 15, 10, 'D', 'Replace only visible damage', FALSE, NULL, 4)
) AS v(part_num, chap_num, question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
JOIN quizzes q ON q.chapter_id = c.id AND q.is_final_exam = FALSE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (2, 16, 1, 'A', 'Up to 24 hours after rain stops', FALSE, NULL, 1),
  (2, 16, 1, 'B', 'Up to 48 hours after rain stops', TRUE, 'Industry standard.', 2),
  (2, 16, 1, 'C', 'Up to one week', FALSE, NULL, 3),
  (2, 16, 1, 'D', 'There is no standard', FALSE, NULL, 4),
  (2, 16, 2, 'A', 'Internal drains', FALSE, NULL, 1),
  (2, 16, 2, 'B', 'Scuppers', FALSE, NULL, 2),
  (2, 16, 2, 'C', 'Edge drainage', FALSE, NULL, 3),
  (2, 16, 2, 'D', 'Capillary action', TRUE, 'Not a drainage approach.', 4),
  (2, 16, 3, 'A', 'The primary drain', FALSE, NULL, 1),
  (2, 16, 3, 'B', 'A secondary drainage point at higher elevation, intended to handle water if primary clogs', TRUE, 'Standard definition.', 2),
  (2, 16, 3, 'C', 'A type of gutter', FALSE, NULL, 3),
  (2, 16, 3, 'D', 'A coating system', FALSE, NULL, 4),
  (2, 16, 4, 'A', 'A type of structural support', FALSE, NULL, 1),
  (2, 16, 4, 'B', 'Dirt accumulation pattern marking where water has been sitting', TRUE, 'Standard inspection indicator.', 2),
  (2, 16, 4, 'C', 'A drainage device', FALSE, NULL, 3),
  (2, 16, 4, 'D', 'A warranty term', FALSE, NULL, 4),
  (2, 16, 5, 'A', 'Fix the ponding by adding slope', FALSE, NULL, 1),
  (2, 16, 5, 'B', 'Not fix the ponding — coatings don''t add slope; coating will likely fail over the ponded area', TRUE, 'Coatings don''t add slope.', 2),
  (2, 16, 5, 'C', 'Last longer than on dry areas', FALSE, NULL, 3),
  (2, 16, 5, 'D', 'Strengthen the roof structure', FALSE, NULL, 4),
  (2, 16, 6, 'A', 'TPO single-ply', FALSE, NULL, 1),
  (2, 16, 6, 'B', 'SPF', TRUE, 'Unique among standard flat-roof systems.', 2),
  (2, 16, 6, 'C', 'Modified bitumen', FALSE, NULL, 3),
  (2, 16, 6, 'D', 'Silicone coating', FALSE, NULL, 4),
  (2, 16, 7, 'A', 'Tell them flat roofs always pond', FALSE, NULL, 1),
  (2, 16, 7, 'B', 'Inspect, document ponding evidence, verify drainage and overflow', TRUE, 'Standard inspection response.', 2),
  (2, 16, 7, 'C', 'Quote a coating immediately', FALSE, NULL, 3),
  (2, 16, 7, 'D', 'Recommend full replacement', FALSE, NULL, 4),
  (2, 16, 8, 'A', 'Climate change', FALSE, NULL, 1),
  (2, 16, 8, 'B', 'Original construction defect', FALSE, NULL, 2),
  (2, 16, 8, 'C', 'Building settlement, deck deflection, or insulation compression over time', TRUE, 'Common causes on aged buildings.', 3),
  (2, 16, 8, 'D', 'Recent paint job', FALSE, NULL, 4),
  (2, 16, 9, 'A', 'Silicone restoration only', FALSE, NULL, 1),
  (2, 16, 9, 'B', 'SPF or replacement with tapered insulation; both address slope', TRUE, 'Real ponding fixes.', 2),
  (2, 16, 9, 'C', 'Add another drain', FALSE, NULL, 3),
  (2, 16, 9, 'D', 'Apply two coats of acrylic', FALSE, NULL, 4),
  (2, 16, 10, 'A', 'Defer to other contractor', FALSE, NULL, 1),
  (2, 16, 10, 'B', 'Tell customer the other contractor was wrong', FALSE, NULL, 2),
  (2, 16, 10, 'C', 'Document what you observed, explain the 48-hour standard, let customer compare', TRUE, 'Honest framework.', 3),
  (2, 16, 10, 'D', 'Decline to provide proposal', FALSE, NULL, 4),
  (2, 17, 1, 'A', 'How much will it cost?', FALSE, NULL, 1),
  (2, 17, 1, 'B', 'What roof system is on the building?', TRUE, 'Foundation of every commercial conversation.', 2),
  (2, 17, 1, 'C', 'Whether customer has insurance', FALSE, NULL, 3),
  (2, 17, 1, 'D', 'Whether customer is owner', FALSE, NULL, 4),
  (2, 17, 2, 'A', 'EPDM', FALSE, NULL, 1),
  (2, 17, 2, 'B', 'TPO or PVC', TRUE, 'Both white welded-seam single-ply.', 2),
  (2, 17, 2, 'C', 'BUR', FALSE, NULL, 3),
  (2, 17, 2, 'D', 'Wood shake', FALSE, NULL, 4),
  (2, 17, 3, 'A', 'TPO', FALSE, NULL, 1),
  (2, 17, 3, 'B', 'PVC', FALSE, NULL, 2),
  (2, 17, 3, 'C', 'EPDM', TRUE, 'Black + non-welded seams = EPDM.', 3),
  (2, 17, 3, 'D', 'SPF', FALSE, NULL, 4),
  (2, 17, 4, 'A', 'TPO', FALSE, NULL, 1),
  (2, 17, 4, 'B', 'PVC', FALSE, NULL, 2),
  (2, 17, 4, 'C', 'Silicone coating only', FALSE, NULL, 3),
  (2, 17, 4, 'D', 'SPF', TRUE, 'Orange-peel = SPF.', 4),
  (2, 17, 5, 'A', 'Confirm TPO based on color', FALSE, NULL, 1),
  (2, 17, 5, 'B', 'Confirm PVC based on slick feel', FALSE, NULL, 2),
  (2, 17, 5, 'C', 'Document visual indicators; note product type cannot be certified without documentation', TRUE, 'Honest framework.', 3),
  (2, 17, 5, 'D', 'Defer to customer''s belief', FALSE, NULL, 4),
  (2, 17, 6, 'A', 'Topcoat color', FALSE, NULL, 1),
  (2, 17, 6, 'B', 'Orange-peel texture characteristic of foam', TRUE, 'Most reliable single indicator.', 2),
  (2, 17, 6, 'C', 'Building age', FALSE, NULL, 3),
  (2, 17, 6, 'D', 'Cost', FALSE, NULL, 4),
  (2, 17, 7, 'A', 'Defer to property manager', FALSE, NULL, 1),
  (2, 17, 7, 'B', 'Document, ask for documentation, escalate if scope depends on certainty', TRUE, 'Honest framework.', 2),
  (2, 17, 7, 'C', 'Tell manager they''re wrong', FALSE, NULL, 3),
  (2, 17, 7, 'D', 'Quote as TPO regardless', FALSE, NULL, 4),
  (2, 17, 8, 'A', 'Identifying coating chemistry', FALSE, NULL, 1),
  (2, 17, 8, 'B', 'Identifying the substrate underneath', TRUE, 'Substrate determines future scope.', 2),
  (2, 17, 8, 'C', 'Counting gravel', FALSE, NULL, 3),
  (2, 17, 8, 'D', 'Measuring slope', FALSE, NULL, 4),
  (2, 17, 9, 'A', 'None special', FALSE, NULL, 1),
  (2, 17, 9, 'B', 'Asbestos potential, layer count assessment, substrate identification', TRUE, 'Pre-1980s considerations.', 2),
  (2, 17, 9, 'C', 'Confirming warranty is current', FALSE, NULL, 3),
  (2, 17, 9, 'D', 'Drone-only inspection', FALSE, NULL, 4),
  (2, 17, 10, 'A', 'TPO', FALSE, NULL, 1),
  (2, 17, 10, 'B', 'PVC', TRUE, 'Restaurant + grease + held up well = PVC.', 2),
  (2, 17, 10, 'C', 'EPDM', FALSE, NULL, 3),
  (2, 17, 10, 'D', 'Modified bitumen', FALSE, NULL, 4),
  (2, 18, 1, 'A', 'Color of roof', FALSE, NULL, 1),
  (2, 18, 1, 'B', 'Granular surface texture', TRUE, 'None of the look-alikes have granular surface.', 2),
  (2, 18, 1, 'C', 'Pitch', FALSE, NULL, 3),
  (2, 18, 1, 'D', 'Age of home', FALSE, NULL, 4),
  (2, 18, 2, 'A', 'Profile shape only', FALSE, NULL, 1),
  (2, 18, 2, 'B', 'Tap sound — concrete dull thud, clay higher-pitched ring', TRUE, 'Most reliable distinguisher.', 2),
  (2, 18, 2, 'C', 'Color always', FALSE, NULL, 3),
  (2, 18, 2, 'D', 'There is no reliable difference', FALSE, NULL, 4),
  (2, 18, 3, 'A', 'Three-tab', FALSE, NULL, 1),
  (2, 18, 3, 'B', 'Two layers bonded together creating shadowed, textured appearance', TRUE, 'Standard description.', 2),
  (2, 18, 3, 'C', 'Designer / luxury', FALSE, NULL, 3),
  (2, 18, 3, 'D', 'Wood shake', FALSE, NULL, 4),
  (2, 18, 4, 'A', 'All residential systems including slate and wood shake', FALSE, NULL, 1),
  (2, 18, 4, 'B', 'Composition shingle (full installation, repair, replacement) and concrete tile (repair and maintenance)', TRUE, 'USA Flat Roof''s specific scope.', 2),
  (2, 18, 4, 'C', 'Composition shingle only', FALSE, NULL, 3),
  (2, 18, 4, 'D', 'Tile only', FALSE, NULL, 4),
  (2, 18, 5, 'A', 'Real clay tile', FALSE, NULL, 1),
  (2, 18, 5, 'B', 'Concrete tile (pigmented or coated to mimic clay)', TRUE, 'Era and tract pattern in NorCal.', 2),
  (2, 18, 5, 'C', 'Stone-coated metal', FALSE, NULL, 3),
  (2, 18, 5, 'D', 'Composition shingle', FALSE, NULL, 4)
) AS v(part_num, chap_num, question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
JOIN quizzes q ON q.chapter_id = c.id AND q.is_final_exam = FALSE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
INSERT INTO quiz_answers (question_id, answer_letter, answer_text, is_correct, explanation, display_order)
SELECT qq.id, v.answer_letter, v.answer_text, v.is_correct, v.explanation, v.display_order
FROM (VALUES
  (2, 18, 6, 'A', 'Real wood shake', FALSE, NULL, 1),
  (2, 18, 6, 'B', 'Synthetic / composite shake', TRUE, 'Plastic-pop tap is the give-away.', 2),
  (2, 18, 6, 'C', 'Composition shake-look shingle', FALSE, NULL, 3),
  (2, 18, 6, 'D', 'Stone-coated metal', FALSE, NULL, 4),
  (2, 18, 7, 'A', 'Concrete tile', FALSE, NULL, 1),
  (2, 18, 7, 'B', 'Real slate', TRUE, 'Era, location, ring, natural variation match.', 2),
  (2, 18, 7, 'C', 'Synthetic slate', FALSE, NULL, 3),
  (2, 18, 7, 'D', 'Composition shingle', FALSE, NULL, 4),
  (2, 18, 8, 'A', 'Quote tile work generically', FALSE, NULL, 1),
  (2, 18, 8, 'B', 'Inspect to identify whether concrete or clay (and profile), since scope depends on it', TRUE, 'Identification before quoting.', 2),
  (2, 18, 8, 'C', 'Decline to inspect', FALSE, NULL, 3),
  (2, 18, 8, 'D', 'Refer to tile contractor without inspection', FALSE, NULL, 4),
  (2, 18, 9, 'A', 'Same approach as composition shingle', FALSE, NULL, 1),
  (2, 18, 9, 'B', 'Commercial-system identification approach (Chapter 17)', TRUE, 'Flat sections require commercial-system framework.', 2),
  (2, 18, 9, 'C', 'No inspection — flat sections don''t matter', FALSE, NULL, 3),
  (2, 18, 9, 'D', 'Drone only', FALSE, NULL, 4),
  (2, 18, 10, 'A', 'Confirm homeowner is correct', FALSE, NULL, 1),
  (2, 18, 10, 'B', 'Document observed (synthetic appearance), explain indicators, ask for documentation', TRUE, 'Honest response.', 2),
  (2, 18, 10, 'C', 'Tell homeowner they''re wrong', FALSE, NULL, 3),
  (2, 18, 10, 'D', 'Quote as real slate based on report', FALSE, NULL, 4)
) AS v(part_num, chap_num, question_number, answer_letter, answer_text, is_correct, explanation, display_order)
JOIN book_parts p ON p.part_number = v.part_num
JOIN chapters c ON c.part_id = p.id AND c.chapter_number = v.chap_num
JOIN quizzes q ON q.chapter_id = c.id AND q.is_final_exam = FALSE
JOIN quiz_questions qq ON qq.quiz_id = q.id AND qq.question_number = v.question_number;
COMMIT;
